/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the WanProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WanProviderOption{}

// WanProviderOption struct for WanProviderOption
type WanProviderOption struct {
	Parameters WanProviderOptionParameters `json:"parameters"`
}

// NewWanProviderOption instantiates a new WanProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWanProviderOption(parameters WanProviderOptionParameters) *WanProviderOption {
	this := WanProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewWanProviderOptionWithDefaults instantiates a new WanProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWanProviderOptionWithDefaults() *WanProviderOption {
	this := WanProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *WanProviderOption) GetParameters() WanProviderOptionParameters {
	if o == nil {
		var ret WanProviderOptionParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *WanProviderOption) GetParametersOk() (*WanProviderOptionParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *WanProviderOption) SetParameters(v WanProviderOptionParameters) {
	o.Parameters = v
}

func (o WanProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WanProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableWanProviderOption struct {
	value *WanProviderOption
	isSet bool
}

func (v NullableWanProviderOption) Get() *WanProviderOption {
	return v.value
}

func (v *NullableWanProviderOption) Set(val *WanProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableWanProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableWanProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWanProviderOption(val *WanProviderOption) *NullableWanProviderOption {
	return &NullableWanProviderOption{value: val, isSet: true}
}

func (v NullableWanProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWanProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
