/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the KwaivgiProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KwaivgiProviderOption{}

// KwaivgiProviderOption struct for KwaivgiProviderOption
type KwaivgiProviderOption struct {
	Parameters KwaivgiParameters `json:"parameters"`
}

// NewKwaivgiProviderOption instantiates a new KwaivgiProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKwaivgiProviderOption(parameters KwaivgiParameters) *KwaivgiProviderOption {
	this := KwaivgiProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewKwaivgiProviderOptionWithDefaults instantiates a new KwaivgiProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKwaivgiProviderOptionWithDefaults() *KwaivgiProviderOption {
	this := KwaivgiProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *KwaivgiProviderOption) GetParameters() KwaivgiParameters {
	if o == nil {
		var ret KwaivgiParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *KwaivgiProviderOption) GetParametersOk() (*KwaivgiParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *KwaivgiProviderOption) SetParameters(v KwaivgiParameters) {
	o.Parameters = v
}

func (o KwaivgiProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KwaivgiProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableKwaivgiProviderOption struct {
	value *KwaivgiProviderOption
	isSet bool
}

func (v NullableKwaivgiProviderOption) Get() *KwaivgiProviderOption {
	return v.value
}

func (v *NullableKwaivgiProviderOption) Set(val *KwaivgiProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableKwaivgiProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableKwaivgiProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKwaivgiProviderOption(val *KwaivgiProviderOption) *NullableKwaivgiProviderOption {
	return &NullableKwaivgiProviderOption{value: val, isSet: true}
}

func (v NullableKwaivgiProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKwaivgiProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
