/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the GoogleProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleProviderOption{}

// GoogleProviderOption struct for GoogleProviderOption
type GoogleProviderOption struct {
	Parameters GoogleProviderOptionParameters `json:"parameters"`
}

// NewGoogleProviderOption instantiates a new GoogleProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleProviderOption(parameters GoogleProviderOptionParameters) *GoogleProviderOption {
	this := GoogleProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewGoogleProviderOptionWithDefaults instantiates a new GoogleProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleProviderOptionWithDefaults() *GoogleProviderOption {
	this := GoogleProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *GoogleProviderOption) GetParameters() GoogleProviderOptionParameters {
	if o == nil {
		var ret GoogleProviderOptionParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *GoogleProviderOption) GetParametersOk() (*GoogleProviderOptionParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *GoogleProviderOption) SetParameters(v GoogleProviderOptionParameters) {
	o.Parameters = v
}

func (o GoogleProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableGoogleProviderOption struct {
	value *GoogleProviderOption
	isSet bool
}

func (v NullableGoogleProviderOption) Get() *GoogleProviderOption {
	return v.value
}

func (v *NullableGoogleProviderOption) Set(val *GoogleProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleProviderOption(val *GoogleProviderOption) *NullableGoogleProviderOption {
	return &NullableGoogleProviderOption{value: val, isSet: true}
}

func (v NullableGoogleProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
