/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedSpeechRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedSpeechRequest{}

// UnifiedSpeechRequest struct for UnifiedSpeechRequest
type UnifiedSpeechRequest struct {
	Model string `json:"model"`
	Input string `json:"input"`
	// Open provider-specific voice ID.
	Voice    string           `json:"voice"`
	Speed    *float64         `json:"speed,omitempty"`
	Provider *ProviderOptions `json:"provider,omitempty"`
}

// NewUnifiedSpeechRequest instantiates a new UnifiedSpeechRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedSpeechRequest(model string, input string, voice string) *UnifiedSpeechRequest {
	this := UnifiedSpeechRequest{}
	this.Model = model
	this.Input = input
	this.Voice = voice
	return &this
}

// NewUnifiedSpeechRequestWithDefaults instantiates a new UnifiedSpeechRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedSpeechRequestWithDefaults() *UnifiedSpeechRequest {
	this := UnifiedSpeechRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedSpeechRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedSpeechRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedSpeechRequest) SetModel(v string) {
	o.Model = v
}

// GetInput returns the Input field value
func (o *UnifiedSpeechRequest) GetInput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *UnifiedSpeechRequest) GetInputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *UnifiedSpeechRequest) SetInput(v string) {
	o.Input = v
}

// GetVoice returns the Voice field value
func (o *UnifiedSpeechRequest) GetVoice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Voice
}

// GetVoiceOk returns a tuple with the Voice field value
// and a boolean to check if the value has been set.
func (o *UnifiedSpeechRequest) GetVoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Voice, true
}

// SetVoice sets field value
func (o *UnifiedSpeechRequest) SetVoice(v string) {
	o.Voice = v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *UnifiedSpeechRequest) GetSpeed() float64 {
	if o == nil || IsNil(o.Speed) {
		var ret float64
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedSpeechRequest) GetSpeedOk() (*float64, bool) {
	if o == nil || IsNil(o.Speed) {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *UnifiedSpeechRequest) HasSpeed() bool {
	if o != nil && !IsNil(o.Speed) {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given float64 and assigns it to the Speed field.
func (o *UnifiedSpeechRequest) SetSpeed(v float64) {
	o.Speed = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedSpeechRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedSpeechRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedSpeechRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedSpeechRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedSpeechRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedSpeechRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["input"] = o.Input
	toSerialize["voice"] = o.Voice
	if !IsNil(o.Speed) {
		toSerialize["speed"] = o.Speed
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedSpeechRequest struct {
	value *UnifiedSpeechRequest
	isSet bool
}

func (v NullableUnifiedSpeechRequest) Get() *UnifiedSpeechRequest {
	return v.value
}

func (v *NullableUnifiedSpeechRequest) Set(val *UnifiedSpeechRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedSpeechRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedSpeechRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedSpeechRequest(val *UnifiedSpeechRequest) *NullableUnifiedSpeechRequest {
	return &NullableUnifiedSpeechRequest{value: val, isSet: true}
}

func (v NullableUnifiedSpeechRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedSpeechRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
