/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the SoraReverseProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoraReverseProviderOptionParameters{}

// SoraReverseProviderOptionParameters struct for SoraReverseProviderOptionParameters
type SoraReverseProviderOptionParameters struct {
	Timestamps   *string `json:"timestamps,omitempty"`
	FromTask     *string `json:"from_task,omitempty"`
	Url          *string `json:"url,omitempty"`
	CharacterUrl *string `json:"character_url,omitempty"`
	Orientation  *string `json:"orientation,omitempty"`
	Show         *bool   `json:"show,omitempty"`
}

// NewSoraReverseProviderOptionParameters instantiates a new SoraReverseProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoraReverseProviderOptionParameters() *SoraReverseProviderOptionParameters {
	this := SoraReverseProviderOptionParameters{}
	return &this
}

// NewSoraReverseProviderOptionParametersWithDefaults instantiates a new SoraReverseProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoraReverseProviderOptionParametersWithDefaults() *SoraReverseProviderOptionParameters {
	this := SoraReverseProviderOptionParameters{}
	return &this
}

// GetTimestamps returns the Timestamps field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetTimestamps() string {
	if o == nil || IsNil(o.Timestamps) {
		var ret string
		return ret
	}
	return *o.Timestamps
}

// GetTimestampsOk returns a tuple with the Timestamps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetTimestampsOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamps) {
		return nil, false
	}
	return o.Timestamps, true
}

// HasTimestamps returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasTimestamps() bool {
	if o != nil && !IsNil(o.Timestamps) {
		return true
	}

	return false
}

// SetTimestamps gets a reference to the given string and assigns it to the Timestamps field.
func (o *SoraReverseProviderOptionParameters) SetTimestamps(v string) {
	o.Timestamps = &v
}

// GetFromTask returns the FromTask field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetFromTask() string {
	if o == nil || IsNil(o.FromTask) {
		var ret string
		return ret
	}
	return *o.FromTask
}

// GetFromTaskOk returns a tuple with the FromTask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetFromTaskOk() (*string, bool) {
	if o == nil || IsNil(o.FromTask) {
		return nil, false
	}
	return o.FromTask, true
}

// HasFromTask returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasFromTask() bool {
	if o != nil && !IsNil(o.FromTask) {
		return true
	}

	return false
}

// SetFromTask gets a reference to the given string and assigns it to the FromTask field.
func (o *SoraReverseProviderOptionParameters) SetFromTask(v string) {
	o.FromTask = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SoraReverseProviderOptionParameters) SetUrl(v string) {
	o.Url = &v
}

// GetCharacterUrl returns the CharacterUrl field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetCharacterUrl() string {
	if o == nil || IsNil(o.CharacterUrl) {
		var ret string
		return ret
	}
	return *o.CharacterUrl
}

// GetCharacterUrlOk returns a tuple with the CharacterUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetCharacterUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CharacterUrl) {
		return nil, false
	}
	return o.CharacterUrl, true
}

// HasCharacterUrl returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasCharacterUrl() bool {
	if o != nil && !IsNil(o.CharacterUrl) {
		return true
	}

	return false
}

// SetCharacterUrl gets a reference to the given string and assigns it to the CharacterUrl field.
func (o *SoraReverseProviderOptionParameters) SetCharacterUrl(v string) {
	o.CharacterUrl = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetOrientation() string {
	if o == nil || IsNil(o.Orientation) {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetOrientationOk() (*string, bool) {
	if o == nil || IsNil(o.Orientation) {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasOrientation() bool {
	if o != nil && !IsNil(o.Orientation) {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *SoraReverseProviderOptionParameters) SetOrientation(v string) {
	o.Orientation = &v
}

// GetShow returns the Show field value if set, zero value otherwise.
func (o *SoraReverseProviderOptionParameters) GetShow() bool {
	if o == nil || IsNil(o.Show) {
		var ret bool
		return ret
	}
	return *o.Show
}

// GetShowOk returns a tuple with the Show field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOptionParameters) GetShowOk() (*bool, bool) {
	if o == nil || IsNil(o.Show) {
		return nil, false
	}
	return o.Show, true
}

// HasShow returns a boolean if a field has been set.
func (o *SoraReverseProviderOptionParameters) HasShow() bool {
	if o != nil && !IsNil(o.Show) {
		return true
	}

	return false
}

// SetShow gets a reference to the given bool and assigns it to the Show field.
func (o *SoraReverseProviderOptionParameters) SetShow(v bool) {
	o.Show = &v
}

func (o SoraReverseProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoraReverseProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamps) {
		toSerialize["timestamps"] = o.Timestamps
	}
	if !IsNil(o.FromTask) {
		toSerialize["from_task"] = o.FromTask
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.CharacterUrl) {
		toSerialize["character_url"] = o.CharacterUrl
	}
	if !IsNil(o.Orientation) {
		toSerialize["orientation"] = o.Orientation
	}
	if !IsNil(o.Show) {
		toSerialize["show"] = o.Show
	}
	return toSerialize, nil
}

type NullableSoraReverseProviderOptionParameters struct {
	value *SoraReverseProviderOptionParameters
	isSet bool
}

func (v NullableSoraReverseProviderOptionParameters) Get() *SoraReverseProviderOptionParameters {
	return v.value
}

func (v *NullableSoraReverseProviderOptionParameters) Set(val *SoraReverseProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableSoraReverseProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableSoraReverseProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoraReverseProviderOptionParameters(val *SoraReverseProviderOptionParameters) *NullableSoraReverseProviderOptionParameters {
	return &NullableSoraReverseProviderOptionParameters{value: val, isSet: true}
}

func (v NullableSoraReverseProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoraReverseProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
