/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedImageRequest{}

// UnifiedImageRequest struct for UnifiedImageRequest
type UnifiedImageRequest struct {
	Model       string            `json:"model"`
	Prompt      string            `json:"prompt"`
	AspectRatio *ImageAspectRatio `json:"aspect_ratio,omitempty"`
	Resolution  *ImageResolution  `json:"resolution,omitempty"`
	// Resolution tier or explicit pixels.
	Size            *string          `json:"size,omitempty"`
	N               *int32           `json:"n,omitempty"`
	Quality         *string          `json:"quality,omitempty"`
	OutputFormat    *string          `json:"output_format,omitempty"`
	Background      *string          `json:"background,omitempty"`
	Seed            *int32           `json:"seed,omitempty"`
	InputReferences []ImageReference `json:"input_references,omitempty"`
	Provider        *ProviderOptions `json:"provider,omitempty"`
}

// NewUnifiedImageRequest instantiates a new UnifiedImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedImageRequest(model string, prompt string) *UnifiedImageRequest {
	this := UnifiedImageRequest{}
	this.Model = model
	this.Prompt = prompt
	return &this
}

// NewUnifiedImageRequestWithDefaults instantiates a new UnifiedImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedImageRequestWithDefaults() *UnifiedImageRequest {
	this := UnifiedImageRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedImageRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedImageRequest) SetModel(v string) {
	o.Model = v
}

// GetPrompt returns the Prompt field value
func (o *UnifiedImageRequest) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *UnifiedImageRequest) SetPrompt(v string) {
	o.Prompt = v
}

// GetAspectRatio returns the AspectRatio field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetAspectRatio() ImageAspectRatio {
	if o == nil || IsNil(o.AspectRatio) {
		var ret ImageAspectRatio
		return ret
	}
	return *o.AspectRatio
}

// GetAspectRatioOk returns a tuple with the AspectRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetAspectRatioOk() (*ImageAspectRatio, bool) {
	if o == nil || IsNil(o.AspectRatio) {
		return nil, false
	}
	return o.AspectRatio, true
}

// HasAspectRatio returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasAspectRatio() bool {
	if o != nil && !IsNil(o.AspectRatio) {
		return true
	}

	return false
}

// SetAspectRatio gets a reference to the given ImageAspectRatio and assigns it to the AspectRatio field.
func (o *UnifiedImageRequest) SetAspectRatio(v ImageAspectRatio) {
	o.AspectRatio = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetResolution() ImageResolution {
	if o == nil || IsNil(o.Resolution) {
		var ret ImageResolution
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetResolutionOk() (*ImageResolution, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given ImageResolution and assigns it to the Resolution field.
func (o *UnifiedImageRequest) SetResolution(v ImageResolution) {
	o.Resolution = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *UnifiedImageRequest) SetSize(v string) {
	o.Size = &v
}

// GetN returns the N field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetN() int32 {
	if o == nil || IsNil(o.N) {
		var ret int32
		return ret
	}
	return *o.N
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetNOk() (*int32, bool) {
	if o == nil || IsNil(o.N) {
		return nil, false
	}
	return o.N, true
}

// HasN returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasN() bool {
	if o != nil && !IsNil(o.N) {
		return true
	}

	return false
}

// SetN gets a reference to the given int32 and assigns it to the N field.
func (o *UnifiedImageRequest) SetN(v int32) {
	o.N = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetQuality() string {
	if o == nil || IsNil(o.Quality) {
		var ret string
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetQualityOk() (*string, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given string and assigns it to the Quality field.
func (o *UnifiedImageRequest) SetQuality(v string) {
	o.Quality = &v
}

// GetOutputFormat returns the OutputFormat field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetOutputFormat() string {
	if o == nil || IsNil(o.OutputFormat) {
		var ret string
		return ret
	}
	return *o.OutputFormat
}

// GetOutputFormatOk returns a tuple with the OutputFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetOutputFormatOk() (*string, bool) {
	if o == nil || IsNil(o.OutputFormat) {
		return nil, false
	}
	return o.OutputFormat, true
}

// HasOutputFormat returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasOutputFormat() bool {
	if o != nil && !IsNil(o.OutputFormat) {
		return true
	}

	return false
}

// SetOutputFormat gets a reference to the given string and assigns it to the OutputFormat field.
func (o *UnifiedImageRequest) SetOutputFormat(v string) {
	o.OutputFormat = &v
}

// GetBackground returns the Background field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetBackground() string {
	if o == nil || IsNil(o.Background) {
		var ret string
		return ret
	}
	return *o.Background
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetBackgroundOk() (*string, bool) {
	if o == nil || IsNil(o.Background) {
		return nil, false
	}
	return o.Background, true
}

// HasBackground returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasBackground() bool {
	if o != nil && !IsNil(o.Background) {
		return true
	}

	return false
}

// SetBackground gets a reference to the given string and assigns it to the Background field.
func (o *UnifiedImageRequest) SetBackground(v string) {
	o.Background = &v
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetSeed() int32 {
	if o == nil || IsNil(o.Seed) {
		var ret int32
		return ret
	}
	return *o.Seed
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetSeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Seed) {
		return nil, false
	}
	return o.Seed, true
}

// HasSeed returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasSeed() bool {
	if o != nil && !IsNil(o.Seed) {
		return true
	}

	return false
}

// SetSeed gets a reference to the given int32 and assigns it to the Seed field.
func (o *UnifiedImageRequest) SetSeed(v int32) {
	o.Seed = &v
}

// GetInputReferences returns the InputReferences field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetInputReferences() []ImageReference {
	if o == nil || IsNil(o.InputReferences) {
		var ret []ImageReference
		return ret
	}
	return o.InputReferences
}

// GetInputReferencesOk returns a tuple with the InputReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetInputReferencesOk() ([]ImageReference, bool) {
	if o == nil || IsNil(o.InputReferences) {
		return nil, false
	}
	return o.InputReferences, true
}

// HasInputReferences returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasInputReferences() bool {
	if o != nil && !IsNil(o.InputReferences) {
		return true
	}

	return false
}

// SetInputReferences gets a reference to the given []ImageReference and assigns it to the InputReferences field.
func (o *UnifiedImageRequest) SetInputReferences(v []ImageReference) {
	o.InputReferences = v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedImageRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedImageRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedImageRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["prompt"] = o.Prompt
	if !IsNil(o.AspectRatio) {
		toSerialize["aspect_ratio"] = o.AspectRatio
	}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.N) {
		toSerialize["n"] = o.N
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !IsNil(o.OutputFormat) {
		toSerialize["output_format"] = o.OutputFormat
	}
	if !IsNil(o.Background) {
		toSerialize["background"] = o.Background
	}
	if !IsNil(o.Seed) {
		toSerialize["seed"] = o.Seed
	}
	if !IsNil(o.InputReferences) {
		toSerialize["input_references"] = o.InputReferences
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedImageRequest struct {
	value *UnifiedImageRequest
	isSet bool
}

func (v NullableUnifiedImageRequest) Get() *UnifiedImageRequest {
	return v.value
}

func (v *NullableUnifiedImageRequest) Set(val *UnifiedImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedImageRequest(val *UnifiedImageRequest) *NullableUnifiedImageRequest {
	return &NullableUnifiedImageRequest{value: val, isSet: true}
}

func (v NullableUnifiedImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
