/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ViduProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViduProviderOption{}

// ViduProviderOption struct for ViduProviderOption
type ViduProviderOption struct {
	Parameters ViduProviderOptionParameters `json:"parameters"`
}

// NewViduProviderOption instantiates a new ViduProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViduProviderOption(parameters ViduProviderOptionParameters) *ViduProviderOption {
	this := ViduProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewViduProviderOptionWithDefaults instantiates a new ViduProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViduProviderOptionWithDefaults() *ViduProviderOption {
	this := ViduProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *ViduProviderOption) GetParameters() ViduProviderOptionParameters {
	if o == nil {
		var ret ViduProviderOptionParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *ViduProviderOption) GetParametersOk() (*ViduProviderOptionParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *ViduProviderOption) SetParameters(v ViduProviderOptionParameters) {
	o.Parameters = v
}

func (o ViduProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViduProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableViduProviderOption struct {
	value *ViduProviderOption
	isSet bool
}

func (v NullableViduProviderOption) Get() *ViduProviderOption {
	return v.value
}

func (v *NullableViduProviderOption) Set(val *ViduProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableViduProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableViduProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViduProviderOption(val *ViduProviderOption) *NullableViduProviderOption {
	return &NullableViduProviderOption{value: val, isSet: true}
}

func (v NullableViduProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViduProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
