/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ProviderOptionsOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderOptionsOptions{}

// ProviderOptionsOptions struct for ProviderOptionsOptions
type ProviderOptionsOptions struct {
	Kwaivgi       *KwaivgiProviderOption     `json:"kwaivgi,omitempty"`
	Kling         *KwaivgiProviderOption     `json:"kling,omitempty"`
	Google        *GoogleProviderOption      `json:"google,omitempty"`
	GoogleVertex  *GoogleProviderOption      `json:"google-vertex,omitempty"`
	Vidu          *ViduProviderOption        `json:"vidu,omitempty"`
	Bytedance     *SeedanceProviderOption    `json:"bytedance,omitempty"`
	Doubao        *SeedanceProviderOption    `json:"doubao,omitempty"`
	Alibaba       *WanProviderOption         `json:"alibaba,omitempty"`
	Wan           *WanProviderOption         `json:"wan,omitempty"`
	Minimax       *MinimaxProviderOption     `json:"minimax,omitempty"`
	OpenaiReverse *SoraReverseProviderOption `json:"openai-reverse,omitempty"`
}

// NewProviderOptionsOptions instantiates a new ProviderOptionsOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderOptionsOptions() *ProviderOptionsOptions {
	this := ProviderOptionsOptions{}
	return &this
}

// NewProviderOptionsOptionsWithDefaults instantiates a new ProviderOptionsOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderOptionsOptionsWithDefaults() *ProviderOptionsOptions {
	this := ProviderOptionsOptions{}
	return &this
}

// GetKwaivgi returns the Kwaivgi field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetKwaivgi() KwaivgiProviderOption {
	if o == nil || IsNil(o.Kwaivgi) {
		var ret KwaivgiProviderOption
		return ret
	}
	return *o.Kwaivgi
}

// GetKwaivgiOk returns a tuple with the Kwaivgi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetKwaivgiOk() (*KwaivgiProviderOption, bool) {
	if o == nil || IsNil(o.Kwaivgi) {
		return nil, false
	}
	return o.Kwaivgi, true
}

// HasKwaivgi returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasKwaivgi() bool {
	if o != nil && !IsNil(o.Kwaivgi) {
		return true
	}

	return false
}

// SetKwaivgi gets a reference to the given KwaivgiProviderOption and assigns it to the Kwaivgi field.
func (o *ProviderOptionsOptions) SetKwaivgi(v KwaivgiProviderOption) {
	o.Kwaivgi = &v
}

// GetKling returns the Kling field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetKling() KwaivgiProviderOption {
	if o == nil || IsNil(o.Kling) {
		var ret KwaivgiProviderOption
		return ret
	}
	return *o.Kling
}

// GetKlingOk returns a tuple with the Kling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetKlingOk() (*KwaivgiProviderOption, bool) {
	if o == nil || IsNil(o.Kling) {
		return nil, false
	}
	return o.Kling, true
}

// HasKling returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasKling() bool {
	if o != nil && !IsNil(o.Kling) {
		return true
	}

	return false
}

// SetKling gets a reference to the given KwaivgiProviderOption and assigns it to the Kling field.
func (o *ProviderOptionsOptions) SetKling(v KwaivgiProviderOption) {
	o.Kling = &v
}

// GetGoogle returns the Google field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetGoogle() GoogleProviderOption {
	if o == nil || IsNil(o.Google) {
		var ret GoogleProviderOption
		return ret
	}
	return *o.Google
}

// GetGoogleOk returns a tuple with the Google field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetGoogleOk() (*GoogleProviderOption, bool) {
	if o == nil || IsNil(o.Google) {
		return nil, false
	}
	return o.Google, true
}

// HasGoogle returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasGoogle() bool {
	if o != nil && !IsNil(o.Google) {
		return true
	}

	return false
}

// SetGoogle gets a reference to the given GoogleProviderOption and assigns it to the Google field.
func (o *ProviderOptionsOptions) SetGoogle(v GoogleProviderOption) {
	o.Google = &v
}

// GetGoogleVertex returns the GoogleVertex field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetGoogleVertex() GoogleProviderOption {
	if o == nil || IsNil(o.GoogleVertex) {
		var ret GoogleProviderOption
		return ret
	}
	return *o.GoogleVertex
}

// GetGoogleVertexOk returns a tuple with the GoogleVertex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetGoogleVertexOk() (*GoogleProviderOption, bool) {
	if o == nil || IsNil(o.GoogleVertex) {
		return nil, false
	}
	return o.GoogleVertex, true
}

// HasGoogleVertex returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasGoogleVertex() bool {
	if o != nil && !IsNil(o.GoogleVertex) {
		return true
	}

	return false
}

// SetGoogleVertex gets a reference to the given GoogleProviderOption and assigns it to the GoogleVertex field.
func (o *ProviderOptionsOptions) SetGoogleVertex(v GoogleProviderOption) {
	o.GoogleVertex = &v
}

// GetVidu returns the Vidu field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetVidu() ViduProviderOption {
	if o == nil || IsNil(o.Vidu) {
		var ret ViduProviderOption
		return ret
	}
	return *o.Vidu
}

// GetViduOk returns a tuple with the Vidu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetViduOk() (*ViduProviderOption, bool) {
	if o == nil || IsNil(o.Vidu) {
		return nil, false
	}
	return o.Vidu, true
}

// HasVidu returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasVidu() bool {
	if o != nil && !IsNil(o.Vidu) {
		return true
	}

	return false
}

// SetVidu gets a reference to the given ViduProviderOption and assigns it to the Vidu field.
func (o *ProviderOptionsOptions) SetVidu(v ViduProviderOption) {
	o.Vidu = &v
}

// GetBytedance returns the Bytedance field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetBytedance() SeedanceProviderOption {
	if o == nil || IsNil(o.Bytedance) {
		var ret SeedanceProviderOption
		return ret
	}
	return *o.Bytedance
}

// GetBytedanceOk returns a tuple with the Bytedance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetBytedanceOk() (*SeedanceProviderOption, bool) {
	if o == nil || IsNil(o.Bytedance) {
		return nil, false
	}
	return o.Bytedance, true
}

// HasBytedance returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasBytedance() bool {
	if o != nil && !IsNil(o.Bytedance) {
		return true
	}

	return false
}

// SetBytedance gets a reference to the given SeedanceProviderOption and assigns it to the Bytedance field.
func (o *ProviderOptionsOptions) SetBytedance(v SeedanceProviderOption) {
	o.Bytedance = &v
}

// GetDoubao returns the Doubao field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetDoubao() SeedanceProviderOption {
	if o == nil || IsNil(o.Doubao) {
		var ret SeedanceProviderOption
		return ret
	}
	return *o.Doubao
}

// GetDoubaoOk returns a tuple with the Doubao field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetDoubaoOk() (*SeedanceProviderOption, bool) {
	if o == nil || IsNil(o.Doubao) {
		return nil, false
	}
	return o.Doubao, true
}

// HasDoubao returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasDoubao() bool {
	if o != nil && !IsNil(o.Doubao) {
		return true
	}

	return false
}

// SetDoubao gets a reference to the given SeedanceProviderOption and assigns it to the Doubao field.
func (o *ProviderOptionsOptions) SetDoubao(v SeedanceProviderOption) {
	o.Doubao = &v
}

// GetAlibaba returns the Alibaba field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetAlibaba() WanProviderOption {
	if o == nil || IsNil(o.Alibaba) {
		var ret WanProviderOption
		return ret
	}
	return *o.Alibaba
}

// GetAlibabaOk returns a tuple with the Alibaba field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetAlibabaOk() (*WanProviderOption, bool) {
	if o == nil || IsNil(o.Alibaba) {
		return nil, false
	}
	return o.Alibaba, true
}

// HasAlibaba returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasAlibaba() bool {
	if o != nil && !IsNil(o.Alibaba) {
		return true
	}

	return false
}

// SetAlibaba gets a reference to the given WanProviderOption and assigns it to the Alibaba field.
func (o *ProviderOptionsOptions) SetAlibaba(v WanProviderOption) {
	o.Alibaba = &v
}

// GetWan returns the Wan field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetWan() WanProviderOption {
	if o == nil || IsNil(o.Wan) {
		var ret WanProviderOption
		return ret
	}
	return *o.Wan
}

// GetWanOk returns a tuple with the Wan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetWanOk() (*WanProviderOption, bool) {
	if o == nil || IsNil(o.Wan) {
		return nil, false
	}
	return o.Wan, true
}

// HasWan returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasWan() bool {
	if o != nil && !IsNil(o.Wan) {
		return true
	}

	return false
}

// SetWan gets a reference to the given WanProviderOption and assigns it to the Wan field.
func (o *ProviderOptionsOptions) SetWan(v WanProviderOption) {
	o.Wan = &v
}

// GetMinimax returns the Minimax field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetMinimax() MinimaxProviderOption {
	if o == nil || IsNil(o.Minimax) {
		var ret MinimaxProviderOption
		return ret
	}
	return *o.Minimax
}

// GetMinimaxOk returns a tuple with the Minimax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetMinimaxOk() (*MinimaxProviderOption, bool) {
	if o == nil || IsNil(o.Minimax) {
		return nil, false
	}
	return o.Minimax, true
}

// HasMinimax returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasMinimax() bool {
	if o != nil && !IsNil(o.Minimax) {
		return true
	}

	return false
}

// SetMinimax gets a reference to the given MinimaxProviderOption and assigns it to the Minimax field.
func (o *ProviderOptionsOptions) SetMinimax(v MinimaxProviderOption) {
	o.Minimax = &v
}

// GetOpenaiReverse returns the OpenaiReverse field value if set, zero value otherwise.
func (o *ProviderOptionsOptions) GetOpenaiReverse() SoraReverseProviderOption {
	if o == nil || IsNil(o.OpenaiReverse) {
		var ret SoraReverseProviderOption
		return ret
	}
	return *o.OpenaiReverse
}

// GetOpenaiReverseOk returns a tuple with the OpenaiReverse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptionsOptions) GetOpenaiReverseOk() (*SoraReverseProviderOption, bool) {
	if o == nil || IsNil(o.OpenaiReverse) {
		return nil, false
	}
	return o.OpenaiReverse, true
}

// HasOpenaiReverse returns a boolean if a field has been set.
func (o *ProviderOptionsOptions) HasOpenaiReverse() bool {
	if o != nil && !IsNil(o.OpenaiReverse) {
		return true
	}

	return false
}

// SetOpenaiReverse gets a reference to the given SoraReverseProviderOption and assigns it to the OpenaiReverse field.
func (o *ProviderOptionsOptions) SetOpenaiReverse(v SoraReverseProviderOption) {
	o.OpenaiReverse = &v
}

func (o ProviderOptionsOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderOptionsOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kwaivgi) {
		toSerialize["kwaivgi"] = o.Kwaivgi
	}
	if !IsNil(o.Kling) {
		toSerialize["kling"] = o.Kling
	}
	if !IsNil(o.Google) {
		toSerialize["google"] = o.Google
	}
	if !IsNil(o.GoogleVertex) {
		toSerialize["google-vertex"] = o.GoogleVertex
	}
	if !IsNil(o.Vidu) {
		toSerialize["vidu"] = o.Vidu
	}
	if !IsNil(o.Bytedance) {
		toSerialize["bytedance"] = o.Bytedance
	}
	if !IsNil(o.Doubao) {
		toSerialize["doubao"] = o.Doubao
	}
	if !IsNil(o.Alibaba) {
		toSerialize["alibaba"] = o.Alibaba
	}
	if !IsNil(o.Wan) {
		toSerialize["wan"] = o.Wan
	}
	if !IsNil(o.Minimax) {
		toSerialize["minimax"] = o.Minimax
	}
	if !IsNil(o.OpenaiReverse) {
		toSerialize["openai-reverse"] = o.OpenaiReverse
	}
	return toSerialize, nil
}

type NullableProviderOptionsOptions struct {
	value *ProviderOptionsOptions
	isSet bool
}

func (v NullableProviderOptionsOptions) Get() *ProviderOptionsOptions {
	return v.value
}

func (v *NullableProviderOptionsOptions) Set(val *ProviderOptionsOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderOptionsOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderOptionsOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderOptionsOptions(val *ProviderOptionsOptions) *NullableProviderOptionsOptions {
	return &NullableProviderOptionsOptions{value: val, isSet: true}
}

func (v NullableProviderOptionsOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderOptionsOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
