/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the FrameImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FrameImage{}

// FrameImage struct for FrameImage
type FrameImage struct {
	Type      string   `json:"type"`
	FrameType string   `json:"frame_type"`
	ImageUrl  ImageUrl `json:"image_url"`
}

// NewFrameImage instantiates a new FrameImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFrameImage(type_ string, frameType string, imageUrl ImageUrl) *FrameImage {
	this := FrameImage{}
	this.Type = type_
	this.FrameType = frameType
	this.ImageUrl = imageUrl
	return &this
}

// NewFrameImageWithDefaults instantiates a new FrameImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFrameImageWithDefaults() *FrameImage {
	this := FrameImage{}
	return &this
}

// GetType returns the Type field value
func (o *FrameImage) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FrameImage) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FrameImage) SetType(v string) {
	o.Type = v
}

// GetFrameType returns the FrameType field value
func (o *FrameImage) GetFrameType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FrameType
}

// GetFrameTypeOk returns a tuple with the FrameType field value
// and a boolean to check if the value has been set.
func (o *FrameImage) GetFrameTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrameType, true
}

// SetFrameType sets field value
func (o *FrameImage) SetFrameType(v string) {
	o.FrameType = v
}

// GetImageUrl returns the ImageUrl field value
func (o *FrameImage) GetImageUrl() ImageUrl {
	if o == nil {
		var ret ImageUrl
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *FrameImage) GetImageUrlOk() (*ImageUrl, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *FrameImage) SetImageUrl(v ImageUrl) {
	o.ImageUrl = v
}

func (o FrameImage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FrameImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["frame_type"] = o.FrameType
	toSerialize["image_url"] = o.ImageUrl
	return toSerialize, nil
}

type NullableFrameImage struct {
	value *FrameImage
	isSet bool
}

func (v NullableFrameImage) Get() *FrameImage {
	return v.value
}

func (v *NullableFrameImage) Set(val *FrameImage) {
	v.value = val
	v.isSet = true
}

func (v NullableFrameImage) IsSet() bool {
	return v.isSet
}

func (v *NullableFrameImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFrameImage(val *FrameImage) *NullableFrameImage {
	return &NullableFrameImage{value: val, isSet: true}
}

func (v NullableFrameImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFrameImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
