/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ViduProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViduProviderOptionParameters{}

// ViduProviderOptionParameters struct for ViduProviderOptionParameters
type ViduProviderOptionParameters struct {
	Subjects          []map[string]interface{} `json:"subjects,omitempty"`
	InputImageN       *int32                   `json:"input_image_n,omitempty"`
	Template          *string                  `json:"template,omitempty"`
	Style             *string                  `json:"style,omitempty"`
	VoiceId           *string                  `json:"voice_id,omitempty"`
	IsRec             *bool                    `json:"is_rec,omitempty"`
	MovementAmplitude *string                  `json:"movement_amplitude,omitempty"`
	Bgm               *bool                    `json:"bgm,omitempty"`
	SampleCount       *int32                   `json:"sample_count,omitempty"`
	Area              *string                  `json:"area,omitempty"`
	Beast             *string                  `json:"beast,omitempty"`
	NegativePrompt    *string                  `json:"negative_prompt,omitempty"`
	Moderation        *string                  `json:"moderation,omitempty"`
}

// NewViduProviderOptionParameters instantiates a new ViduProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViduProviderOptionParameters() *ViduProviderOptionParameters {
	this := ViduProviderOptionParameters{}
	return &this
}

// NewViduProviderOptionParametersWithDefaults instantiates a new ViduProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViduProviderOptionParametersWithDefaults() *ViduProviderOptionParameters {
	this := ViduProviderOptionParameters{}
	return &this
}

// GetSubjects returns the Subjects field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetSubjects() []map[string]interface{} {
	if o == nil || IsNil(o.Subjects) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Subjects
}

// GetSubjectsOk returns a tuple with the Subjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetSubjectsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Subjects) {
		return nil, false
	}
	return o.Subjects, true
}

// HasSubjects returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasSubjects() bool {
	if o != nil && !IsNil(o.Subjects) {
		return true
	}

	return false
}

// SetSubjects gets a reference to the given []map[string]interface{} and assigns it to the Subjects field.
func (o *ViduProviderOptionParameters) SetSubjects(v []map[string]interface{}) {
	o.Subjects = v
}

// GetInputImageN returns the InputImageN field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetInputImageN() int32 {
	if o == nil || IsNil(o.InputImageN) {
		var ret int32
		return ret
	}
	return *o.InputImageN
}

// GetInputImageNOk returns a tuple with the InputImageN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetInputImageNOk() (*int32, bool) {
	if o == nil || IsNil(o.InputImageN) {
		return nil, false
	}
	return o.InputImageN, true
}

// HasInputImageN returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasInputImageN() bool {
	if o != nil && !IsNil(o.InputImageN) {
		return true
	}

	return false
}

// SetInputImageN gets a reference to the given int32 and assigns it to the InputImageN field.
func (o *ViduProviderOptionParameters) SetInputImageN(v int32) {
	o.InputImageN = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *ViduProviderOptionParameters) SetTemplate(v string) {
	o.Template = &v
}

// GetStyle returns the Style field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetStyle() string {
	if o == nil || IsNil(o.Style) {
		var ret string
		return ret
	}
	return *o.Style
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetStyleOk() (*string, bool) {
	if o == nil || IsNil(o.Style) {
		return nil, false
	}
	return o.Style, true
}

// HasStyle returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasStyle() bool {
	if o != nil && !IsNil(o.Style) {
		return true
	}

	return false
}

// SetStyle gets a reference to the given string and assigns it to the Style field.
func (o *ViduProviderOptionParameters) SetStyle(v string) {
	o.Style = &v
}

// GetVoiceId returns the VoiceId field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetVoiceId() string {
	if o == nil || IsNil(o.VoiceId) {
		var ret string
		return ret
	}
	return *o.VoiceId
}

// GetVoiceIdOk returns a tuple with the VoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetVoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.VoiceId) {
		return nil, false
	}
	return o.VoiceId, true
}

// HasVoiceId returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasVoiceId() bool {
	if o != nil && !IsNil(o.VoiceId) {
		return true
	}

	return false
}

// SetVoiceId gets a reference to the given string and assigns it to the VoiceId field.
func (o *ViduProviderOptionParameters) SetVoiceId(v string) {
	o.VoiceId = &v
}

// GetIsRec returns the IsRec field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetIsRec() bool {
	if o == nil || IsNil(o.IsRec) {
		var ret bool
		return ret
	}
	return *o.IsRec
}

// GetIsRecOk returns a tuple with the IsRec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetIsRecOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRec) {
		return nil, false
	}
	return o.IsRec, true
}

// HasIsRec returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasIsRec() bool {
	if o != nil && !IsNil(o.IsRec) {
		return true
	}

	return false
}

// SetIsRec gets a reference to the given bool and assigns it to the IsRec field.
func (o *ViduProviderOptionParameters) SetIsRec(v bool) {
	o.IsRec = &v
}

// GetMovementAmplitude returns the MovementAmplitude field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetMovementAmplitude() string {
	if o == nil || IsNil(o.MovementAmplitude) {
		var ret string
		return ret
	}
	return *o.MovementAmplitude
}

// GetMovementAmplitudeOk returns a tuple with the MovementAmplitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetMovementAmplitudeOk() (*string, bool) {
	if o == nil || IsNil(o.MovementAmplitude) {
		return nil, false
	}
	return o.MovementAmplitude, true
}

// HasMovementAmplitude returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasMovementAmplitude() bool {
	if o != nil && !IsNil(o.MovementAmplitude) {
		return true
	}

	return false
}

// SetMovementAmplitude gets a reference to the given string and assigns it to the MovementAmplitude field.
func (o *ViduProviderOptionParameters) SetMovementAmplitude(v string) {
	o.MovementAmplitude = &v
}

// GetBgm returns the Bgm field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetBgm() bool {
	if o == nil || IsNil(o.Bgm) {
		var ret bool
		return ret
	}
	return *o.Bgm
}

// GetBgmOk returns a tuple with the Bgm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetBgmOk() (*bool, bool) {
	if o == nil || IsNil(o.Bgm) {
		return nil, false
	}
	return o.Bgm, true
}

// HasBgm returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasBgm() bool {
	if o != nil && !IsNil(o.Bgm) {
		return true
	}

	return false
}

// SetBgm gets a reference to the given bool and assigns it to the Bgm field.
func (o *ViduProviderOptionParameters) SetBgm(v bool) {
	o.Bgm = &v
}

// GetSampleCount returns the SampleCount field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetSampleCount() int32 {
	if o == nil || IsNil(o.SampleCount) {
		var ret int32
		return ret
	}
	return *o.SampleCount
}

// GetSampleCountOk returns a tuple with the SampleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetSampleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SampleCount) {
		return nil, false
	}
	return o.SampleCount, true
}

// HasSampleCount returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasSampleCount() bool {
	if o != nil && !IsNil(o.SampleCount) {
		return true
	}

	return false
}

// SetSampleCount gets a reference to the given int32 and assigns it to the SampleCount field.
func (o *ViduProviderOptionParameters) SetSampleCount(v int32) {
	o.SampleCount = &v
}

// GetArea returns the Area field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetArea() string {
	if o == nil || IsNil(o.Area) {
		var ret string
		return ret
	}
	return *o.Area
}

// GetAreaOk returns a tuple with the Area field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetAreaOk() (*string, bool) {
	if o == nil || IsNil(o.Area) {
		return nil, false
	}
	return o.Area, true
}

// HasArea returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasArea() bool {
	if o != nil && !IsNil(o.Area) {
		return true
	}

	return false
}

// SetArea gets a reference to the given string and assigns it to the Area field.
func (o *ViduProviderOptionParameters) SetArea(v string) {
	o.Area = &v
}

// GetBeast returns the Beast field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetBeast() string {
	if o == nil || IsNil(o.Beast) {
		var ret string
		return ret
	}
	return *o.Beast
}

// GetBeastOk returns a tuple with the Beast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetBeastOk() (*string, bool) {
	if o == nil || IsNil(o.Beast) {
		return nil, false
	}
	return o.Beast, true
}

// HasBeast returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasBeast() bool {
	if o != nil && !IsNil(o.Beast) {
		return true
	}

	return false
}

// SetBeast gets a reference to the given string and assigns it to the Beast field.
func (o *ViduProviderOptionParameters) SetBeast(v string) {
	o.Beast = &v
}

// GetNegativePrompt returns the NegativePrompt field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetNegativePrompt() string {
	if o == nil || IsNil(o.NegativePrompt) {
		var ret string
		return ret
	}
	return *o.NegativePrompt
}

// GetNegativePromptOk returns a tuple with the NegativePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetNegativePromptOk() (*string, bool) {
	if o == nil || IsNil(o.NegativePrompt) {
		return nil, false
	}
	return o.NegativePrompt, true
}

// HasNegativePrompt returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasNegativePrompt() bool {
	if o != nil && !IsNil(o.NegativePrompt) {
		return true
	}

	return false
}

// SetNegativePrompt gets a reference to the given string and assigns it to the NegativePrompt field.
func (o *ViduProviderOptionParameters) SetNegativePrompt(v string) {
	o.NegativePrompt = &v
}

// GetModeration returns the Moderation field value if set, zero value otherwise.
func (o *ViduProviderOptionParameters) GetModeration() string {
	if o == nil || IsNil(o.Moderation) {
		var ret string
		return ret
	}
	return *o.Moderation
}

// GetModerationOk returns a tuple with the Moderation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViduProviderOptionParameters) GetModerationOk() (*string, bool) {
	if o == nil || IsNil(o.Moderation) {
		return nil, false
	}
	return o.Moderation, true
}

// HasModeration returns a boolean if a field has been set.
func (o *ViduProviderOptionParameters) HasModeration() bool {
	if o != nil && !IsNil(o.Moderation) {
		return true
	}

	return false
}

// SetModeration gets a reference to the given string and assigns it to the Moderation field.
func (o *ViduProviderOptionParameters) SetModeration(v string) {
	o.Moderation = &v
}

func (o ViduProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViduProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subjects) {
		toSerialize["subjects"] = o.Subjects
	}
	if !IsNil(o.InputImageN) {
		toSerialize["input_image_n"] = o.InputImageN
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.Style) {
		toSerialize["style"] = o.Style
	}
	if !IsNil(o.VoiceId) {
		toSerialize["voice_id"] = o.VoiceId
	}
	if !IsNil(o.IsRec) {
		toSerialize["is_rec"] = o.IsRec
	}
	if !IsNil(o.MovementAmplitude) {
		toSerialize["movement_amplitude"] = o.MovementAmplitude
	}
	if !IsNil(o.Bgm) {
		toSerialize["bgm"] = o.Bgm
	}
	if !IsNil(o.SampleCount) {
		toSerialize["sample_count"] = o.SampleCount
	}
	if !IsNil(o.Area) {
		toSerialize["area"] = o.Area
	}
	if !IsNil(o.Beast) {
		toSerialize["beast"] = o.Beast
	}
	if !IsNil(o.NegativePrompt) {
		toSerialize["negative_prompt"] = o.NegativePrompt
	}
	if !IsNil(o.Moderation) {
		toSerialize["moderation"] = o.Moderation
	}
	return toSerialize, nil
}

type NullableViduProviderOptionParameters struct {
	value *ViduProviderOptionParameters
	isSet bool
}

func (v NullableViduProviderOptionParameters) Get() *ViduProviderOptionParameters {
	return v.value
}

func (v *NullableViduProviderOptionParameters) Set(val *ViduProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableViduProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableViduProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViduProviderOptionParameters(val *ViduProviderOptionParameters) *NullableViduProviderOptionParameters {
	return &NullableViduProviderOptionParameters{value: val, isSet: true}
}

func (v NullableViduProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViduProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
