/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
	"fmt"
)

// VideoResolution 512, 512p, 540p and 768p are retained gptproto provider extensions.
type VideoResolution string

// List of VideoResolution
const (
	VIDEORESOLUTION_RESOLUTION_480P  VideoResolution = "480p"
	VIDEORESOLUTION_RESOLUTION_720P  VideoResolution = "720p"
	VIDEORESOLUTION_RESOLUTION_1080P VideoResolution = "1080p"
	VIDEORESOLUTION_RESOLUTION_1K    VideoResolution = "1K"
	VIDEORESOLUTION_RESOLUTION_2K    VideoResolution = "2K"
	VIDEORESOLUTION_RESOLUTION_4K    VideoResolution = "4K"
	VIDEORESOLUTION_RESOLUTION_512   VideoResolution = "512"
	VIDEORESOLUTION_RESOLUTION_512P  VideoResolution = "512p"
	VIDEORESOLUTION_RESOLUTION_540P  VideoResolution = "540p"
	VIDEORESOLUTION_RESOLUTION_768P  VideoResolution = "768p"
)

// All allowed values of VideoResolution enum
var AllowedVideoResolutionEnumValues = []VideoResolution{
	"480p",
	"720p",
	"1080p",
	"1K",
	"2K",
	"4K",
	"512",
	"512p",
	"540p",
	"768p",
}

func (v *VideoResolution) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VideoResolution(value)
	for _, existing := range AllowedVideoResolutionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VideoResolution", value)
}

// NewVideoResolutionFromValue returns a pointer to a valid VideoResolution
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVideoResolutionFromValue(v string) (*VideoResolution, error) {
	ev := VideoResolution(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VideoResolution: valid values are %v", v, AllowedVideoResolutionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VideoResolution) IsValid() bool {
	for _, existing := range AllowedVideoResolutionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VideoResolution value
func (v VideoResolution) Ptr() *VideoResolution {
	return &v
}

type NullableVideoResolution struct {
	value *VideoResolution
	isSet bool
}

func (v NullableVideoResolution) Get() *VideoResolution {
	return v.value
}

func (v *NullableVideoResolution) Set(val *VideoResolution) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoResolution) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoResolution(val *VideoResolution) *NullableVideoResolution {
	return &NullableVideoResolution{value: val, isSet: true}
}

func (v NullableVideoResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
