/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the KwaivgiParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KwaivgiParameters{}

// KwaivgiParameters struct for KwaivgiParameters
type KwaivgiParameters struct {
	VoiceId              *string                  `json:"voice_id,omitempty"`
	VoiceLanguage        *string                  `json:"voice_language,omitempty"`
	VoiceSpeed           *float32                 `json:"voice_speed,omitempty"`
	GuidanceScale        *float32                 `json:"guidance_scale,omitempty"`
	N                    *int32                   `json:"n,omitempty"`
	CfgScale             *float32                 `json:"cfg_scale,omitempty"`
	UseCustomVoice       *bool                    `json:"use_custom_voice,omitempty"`
	UseCustomVideo       *bool                    `json:"use_custom_video,omitempty"`
	VideoId              *string                  `json:"video_id,omitempty"`
	VideoUrl             *string                  `json:"video_url,omitempty"`
	SoundEffectPrompt    *string                  `json:"sound_effect_prompt,omitempty"`
	BgmPrompt            *string                  `json:"bgm_prompt,omitempty"`
	AsmrMode             *bool                    `json:"asmr_mode,omitempty"`
	Text                 *string                  `json:"text,omitempty"`
	KeepOriginalSound    *bool                    `json:"keep_original_sound,omitempty"`
	CharacterOrientation *string                  `json:"character_orientation,omitempty"`
	ShotType             *string                  `json:"shot_type,omitempty"`
	VoiceList            []map[string]interface{} `json:"voice_list,omitempty"`
	MultiPrompt          []map[string]interface{} `json:"multi_prompt,omitempty"`
	NegativePrompt       *string                  `json:"negative_prompt,omitempty"`
}

// NewKwaivgiParameters instantiates a new KwaivgiParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKwaivgiParameters() *KwaivgiParameters {
	this := KwaivgiParameters{}
	return &this
}

// NewKwaivgiParametersWithDefaults instantiates a new KwaivgiParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKwaivgiParametersWithDefaults() *KwaivgiParameters {
	this := KwaivgiParameters{}
	return &this
}

// GetVoiceId returns the VoiceId field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVoiceId() string {
	if o == nil || IsNil(o.VoiceId) {
		var ret string
		return ret
	}
	return *o.VoiceId
}

// GetVoiceIdOk returns a tuple with the VoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.VoiceId) {
		return nil, false
	}
	return o.VoiceId, true
}

// HasVoiceId returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVoiceId() bool {
	if o != nil && !IsNil(o.VoiceId) {
		return true
	}

	return false
}

// SetVoiceId gets a reference to the given string and assigns it to the VoiceId field.
func (o *KwaivgiParameters) SetVoiceId(v string) {
	o.VoiceId = &v
}

// GetVoiceLanguage returns the VoiceLanguage field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVoiceLanguage() string {
	if o == nil || IsNil(o.VoiceLanguage) {
		var ret string
		return ret
	}
	return *o.VoiceLanguage
}

// GetVoiceLanguageOk returns a tuple with the VoiceLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVoiceLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.VoiceLanguage) {
		return nil, false
	}
	return o.VoiceLanguage, true
}

// HasVoiceLanguage returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVoiceLanguage() bool {
	if o != nil && !IsNil(o.VoiceLanguage) {
		return true
	}

	return false
}

// SetVoiceLanguage gets a reference to the given string and assigns it to the VoiceLanguage field.
func (o *KwaivgiParameters) SetVoiceLanguage(v string) {
	o.VoiceLanguage = &v
}

// GetVoiceSpeed returns the VoiceSpeed field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVoiceSpeed() float32 {
	if o == nil || IsNil(o.VoiceSpeed) {
		var ret float32
		return ret
	}
	return *o.VoiceSpeed
}

// GetVoiceSpeedOk returns a tuple with the VoiceSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVoiceSpeedOk() (*float32, bool) {
	if o == nil || IsNil(o.VoiceSpeed) {
		return nil, false
	}
	return o.VoiceSpeed, true
}

// HasVoiceSpeed returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVoiceSpeed() bool {
	if o != nil && !IsNil(o.VoiceSpeed) {
		return true
	}

	return false
}

// SetVoiceSpeed gets a reference to the given float32 and assigns it to the VoiceSpeed field.
func (o *KwaivgiParameters) SetVoiceSpeed(v float32) {
	o.VoiceSpeed = &v
}

// GetGuidanceScale returns the GuidanceScale field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetGuidanceScale() float32 {
	if o == nil || IsNil(o.GuidanceScale) {
		var ret float32
		return ret
	}
	return *o.GuidanceScale
}

// GetGuidanceScaleOk returns a tuple with the GuidanceScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetGuidanceScaleOk() (*float32, bool) {
	if o == nil || IsNil(o.GuidanceScale) {
		return nil, false
	}
	return o.GuidanceScale, true
}

// HasGuidanceScale returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasGuidanceScale() bool {
	if o != nil && !IsNil(o.GuidanceScale) {
		return true
	}

	return false
}

// SetGuidanceScale gets a reference to the given float32 and assigns it to the GuidanceScale field.
func (o *KwaivgiParameters) SetGuidanceScale(v float32) {
	o.GuidanceScale = &v
}

// GetN returns the N field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetN() int32 {
	if o == nil || IsNil(o.N) {
		var ret int32
		return ret
	}
	return *o.N
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetNOk() (*int32, bool) {
	if o == nil || IsNil(o.N) {
		return nil, false
	}
	return o.N, true
}

// HasN returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasN() bool {
	if o != nil && !IsNil(o.N) {
		return true
	}

	return false
}

// SetN gets a reference to the given int32 and assigns it to the N field.
func (o *KwaivgiParameters) SetN(v int32) {
	o.N = &v
}

// GetCfgScale returns the CfgScale field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetCfgScale() float32 {
	if o == nil || IsNil(o.CfgScale) {
		var ret float32
		return ret
	}
	return *o.CfgScale
}

// GetCfgScaleOk returns a tuple with the CfgScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetCfgScaleOk() (*float32, bool) {
	if o == nil || IsNil(o.CfgScale) {
		return nil, false
	}
	return o.CfgScale, true
}

// HasCfgScale returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasCfgScale() bool {
	if o != nil && !IsNil(o.CfgScale) {
		return true
	}

	return false
}

// SetCfgScale gets a reference to the given float32 and assigns it to the CfgScale field.
func (o *KwaivgiParameters) SetCfgScale(v float32) {
	o.CfgScale = &v
}

// GetUseCustomVoice returns the UseCustomVoice field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetUseCustomVoice() bool {
	if o == nil || IsNil(o.UseCustomVoice) {
		var ret bool
		return ret
	}
	return *o.UseCustomVoice
}

// GetUseCustomVoiceOk returns a tuple with the UseCustomVoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetUseCustomVoiceOk() (*bool, bool) {
	if o == nil || IsNil(o.UseCustomVoice) {
		return nil, false
	}
	return o.UseCustomVoice, true
}

// HasUseCustomVoice returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasUseCustomVoice() bool {
	if o != nil && !IsNil(o.UseCustomVoice) {
		return true
	}

	return false
}

// SetUseCustomVoice gets a reference to the given bool and assigns it to the UseCustomVoice field.
func (o *KwaivgiParameters) SetUseCustomVoice(v bool) {
	o.UseCustomVoice = &v
}

// GetUseCustomVideo returns the UseCustomVideo field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetUseCustomVideo() bool {
	if o == nil || IsNil(o.UseCustomVideo) {
		var ret bool
		return ret
	}
	return *o.UseCustomVideo
}

// GetUseCustomVideoOk returns a tuple with the UseCustomVideo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetUseCustomVideoOk() (*bool, bool) {
	if o == nil || IsNil(o.UseCustomVideo) {
		return nil, false
	}
	return o.UseCustomVideo, true
}

// HasUseCustomVideo returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasUseCustomVideo() bool {
	if o != nil && !IsNil(o.UseCustomVideo) {
		return true
	}

	return false
}

// SetUseCustomVideo gets a reference to the given bool and assigns it to the UseCustomVideo field.
func (o *KwaivgiParameters) SetUseCustomVideo(v bool) {
	o.UseCustomVideo = &v
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVideoId() string {
	if o == nil || IsNil(o.VideoId) {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVideoIdOk() (*string, bool) {
	if o == nil || IsNil(o.VideoId) {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVideoId() bool {
	if o != nil && !IsNil(o.VideoId) {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *KwaivgiParameters) SetVideoId(v string) {
	o.VideoId = &v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVideoUrl() string {
	if o == nil || IsNil(o.VideoUrl) {
		var ret string
		return ret
	}
	return *o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVideoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.VideoUrl) {
		return nil, false
	}
	return o.VideoUrl, true
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVideoUrl() bool {
	if o != nil && !IsNil(o.VideoUrl) {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given string and assigns it to the VideoUrl field.
func (o *KwaivgiParameters) SetVideoUrl(v string) {
	o.VideoUrl = &v
}

// GetSoundEffectPrompt returns the SoundEffectPrompt field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetSoundEffectPrompt() string {
	if o == nil || IsNil(o.SoundEffectPrompt) {
		var ret string
		return ret
	}
	return *o.SoundEffectPrompt
}

// GetSoundEffectPromptOk returns a tuple with the SoundEffectPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetSoundEffectPromptOk() (*string, bool) {
	if o == nil || IsNil(o.SoundEffectPrompt) {
		return nil, false
	}
	return o.SoundEffectPrompt, true
}

// HasSoundEffectPrompt returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasSoundEffectPrompt() bool {
	if o != nil && !IsNil(o.SoundEffectPrompt) {
		return true
	}

	return false
}

// SetSoundEffectPrompt gets a reference to the given string and assigns it to the SoundEffectPrompt field.
func (o *KwaivgiParameters) SetSoundEffectPrompt(v string) {
	o.SoundEffectPrompt = &v
}

// GetBgmPrompt returns the BgmPrompt field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetBgmPrompt() string {
	if o == nil || IsNil(o.BgmPrompt) {
		var ret string
		return ret
	}
	return *o.BgmPrompt
}

// GetBgmPromptOk returns a tuple with the BgmPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetBgmPromptOk() (*string, bool) {
	if o == nil || IsNil(o.BgmPrompt) {
		return nil, false
	}
	return o.BgmPrompt, true
}

// HasBgmPrompt returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasBgmPrompt() bool {
	if o != nil && !IsNil(o.BgmPrompt) {
		return true
	}

	return false
}

// SetBgmPrompt gets a reference to the given string and assigns it to the BgmPrompt field.
func (o *KwaivgiParameters) SetBgmPrompt(v string) {
	o.BgmPrompt = &v
}

// GetAsmrMode returns the AsmrMode field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetAsmrMode() bool {
	if o == nil || IsNil(o.AsmrMode) {
		var ret bool
		return ret
	}
	return *o.AsmrMode
}

// GetAsmrModeOk returns a tuple with the AsmrMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetAsmrModeOk() (*bool, bool) {
	if o == nil || IsNil(o.AsmrMode) {
		return nil, false
	}
	return o.AsmrMode, true
}

// HasAsmrMode returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasAsmrMode() bool {
	if o != nil && !IsNil(o.AsmrMode) {
		return true
	}

	return false
}

// SetAsmrMode gets a reference to the given bool and assigns it to the AsmrMode field.
func (o *KwaivgiParameters) SetAsmrMode(v bool) {
	o.AsmrMode = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *KwaivgiParameters) SetText(v string) {
	o.Text = &v
}

// GetKeepOriginalSound returns the KeepOriginalSound field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetKeepOriginalSound() bool {
	if o == nil || IsNil(o.KeepOriginalSound) {
		var ret bool
		return ret
	}
	return *o.KeepOriginalSound
}

// GetKeepOriginalSoundOk returns a tuple with the KeepOriginalSound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetKeepOriginalSoundOk() (*bool, bool) {
	if o == nil || IsNil(o.KeepOriginalSound) {
		return nil, false
	}
	return o.KeepOriginalSound, true
}

// HasKeepOriginalSound returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasKeepOriginalSound() bool {
	if o != nil && !IsNil(o.KeepOriginalSound) {
		return true
	}

	return false
}

// SetKeepOriginalSound gets a reference to the given bool and assigns it to the KeepOriginalSound field.
func (o *KwaivgiParameters) SetKeepOriginalSound(v bool) {
	o.KeepOriginalSound = &v
}

// GetCharacterOrientation returns the CharacterOrientation field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetCharacterOrientation() string {
	if o == nil || IsNil(o.CharacterOrientation) {
		var ret string
		return ret
	}
	return *o.CharacterOrientation
}

// GetCharacterOrientationOk returns a tuple with the CharacterOrientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetCharacterOrientationOk() (*string, bool) {
	if o == nil || IsNil(o.CharacterOrientation) {
		return nil, false
	}
	return o.CharacterOrientation, true
}

// HasCharacterOrientation returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasCharacterOrientation() bool {
	if o != nil && !IsNil(o.CharacterOrientation) {
		return true
	}

	return false
}

// SetCharacterOrientation gets a reference to the given string and assigns it to the CharacterOrientation field.
func (o *KwaivgiParameters) SetCharacterOrientation(v string) {
	o.CharacterOrientation = &v
}

// GetShotType returns the ShotType field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetShotType() string {
	if o == nil || IsNil(o.ShotType) {
		var ret string
		return ret
	}
	return *o.ShotType
}

// GetShotTypeOk returns a tuple with the ShotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetShotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ShotType) {
		return nil, false
	}
	return o.ShotType, true
}

// HasShotType returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasShotType() bool {
	if o != nil && !IsNil(o.ShotType) {
		return true
	}

	return false
}

// SetShotType gets a reference to the given string and assigns it to the ShotType field.
func (o *KwaivgiParameters) SetShotType(v string) {
	o.ShotType = &v
}

// GetVoiceList returns the VoiceList field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetVoiceList() []map[string]interface{} {
	if o == nil || IsNil(o.VoiceList) {
		var ret []map[string]interface{}
		return ret
	}
	return o.VoiceList
}

// GetVoiceListOk returns a tuple with the VoiceList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetVoiceListOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.VoiceList) {
		return nil, false
	}
	return o.VoiceList, true
}

// HasVoiceList returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasVoiceList() bool {
	if o != nil && !IsNil(o.VoiceList) {
		return true
	}

	return false
}

// SetVoiceList gets a reference to the given []map[string]interface{} and assigns it to the VoiceList field.
func (o *KwaivgiParameters) SetVoiceList(v []map[string]interface{}) {
	o.VoiceList = v
}

// GetMultiPrompt returns the MultiPrompt field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetMultiPrompt() []map[string]interface{} {
	if o == nil || IsNil(o.MultiPrompt) {
		var ret []map[string]interface{}
		return ret
	}
	return o.MultiPrompt
}

// GetMultiPromptOk returns a tuple with the MultiPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetMultiPromptOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.MultiPrompt) {
		return nil, false
	}
	return o.MultiPrompt, true
}

// HasMultiPrompt returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasMultiPrompt() bool {
	if o != nil && !IsNil(o.MultiPrompt) {
		return true
	}

	return false
}

// SetMultiPrompt gets a reference to the given []map[string]interface{} and assigns it to the MultiPrompt field.
func (o *KwaivgiParameters) SetMultiPrompt(v []map[string]interface{}) {
	o.MultiPrompt = v
}

// GetNegativePrompt returns the NegativePrompt field value if set, zero value otherwise.
func (o *KwaivgiParameters) GetNegativePrompt() string {
	if o == nil || IsNil(o.NegativePrompt) {
		var ret string
		return ret
	}
	return *o.NegativePrompt
}

// GetNegativePromptOk returns a tuple with the NegativePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KwaivgiParameters) GetNegativePromptOk() (*string, bool) {
	if o == nil || IsNil(o.NegativePrompt) {
		return nil, false
	}
	return o.NegativePrompt, true
}

// HasNegativePrompt returns a boolean if a field has been set.
func (o *KwaivgiParameters) HasNegativePrompt() bool {
	if o != nil && !IsNil(o.NegativePrompt) {
		return true
	}

	return false
}

// SetNegativePrompt gets a reference to the given string and assigns it to the NegativePrompt field.
func (o *KwaivgiParameters) SetNegativePrompt(v string) {
	o.NegativePrompt = &v
}

func (o KwaivgiParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KwaivgiParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VoiceId) {
		toSerialize["voice_id"] = o.VoiceId
	}
	if !IsNil(o.VoiceLanguage) {
		toSerialize["voice_language"] = o.VoiceLanguage
	}
	if !IsNil(o.VoiceSpeed) {
		toSerialize["voice_speed"] = o.VoiceSpeed
	}
	if !IsNil(o.GuidanceScale) {
		toSerialize["guidance_scale"] = o.GuidanceScale
	}
	if !IsNil(o.N) {
		toSerialize["n"] = o.N
	}
	if !IsNil(o.CfgScale) {
		toSerialize["cfg_scale"] = o.CfgScale
	}
	if !IsNil(o.UseCustomVoice) {
		toSerialize["use_custom_voice"] = o.UseCustomVoice
	}
	if !IsNil(o.UseCustomVideo) {
		toSerialize["use_custom_video"] = o.UseCustomVideo
	}
	if !IsNil(o.VideoId) {
		toSerialize["video_id"] = o.VideoId
	}
	if !IsNil(o.VideoUrl) {
		toSerialize["video_url"] = o.VideoUrl
	}
	if !IsNil(o.SoundEffectPrompt) {
		toSerialize["sound_effect_prompt"] = o.SoundEffectPrompt
	}
	if !IsNil(o.BgmPrompt) {
		toSerialize["bgm_prompt"] = o.BgmPrompt
	}
	if !IsNil(o.AsmrMode) {
		toSerialize["asmr_mode"] = o.AsmrMode
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.KeepOriginalSound) {
		toSerialize["keep_original_sound"] = o.KeepOriginalSound
	}
	if !IsNil(o.CharacterOrientation) {
		toSerialize["character_orientation"] = o.CharacterOrientation
	}
	if !IsNil(o.ShotType) {
		toSerialize["shot_type"] = o.ShotType
	}
	if !IsNil(o.VoiceList) {
		toSerialize["voice_list"] = o.VoiceList
	}
	if !IsNil(o.MultiPrompt) {
		toSerialize["multi_prompt"] = o.MultiPrompt
	}
	if !IsNil(o.NegativePrompt) {
		toSerialize["negative_prompt"] = o.NegativePrompt
	}
	return toSerialize, nil
}

type NullableKwaivgiParameters struct {
	value *KwaivgiParameters
	isSet bool
}

func (v NullableKwaivgiParameters) Get() *KwaivgiParameters {
	return v.value
}

func (v *NullableKwaivgiParameters) Set(val *KwaivgiParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableKwaivgiParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableKwaivgiParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKwaivgiParameters(val *KwaivgiParameters) *NullableKwaivgiParameters {
	return &NullableKwaivgiParameters{value: val, isSet: true}
}

func (v NullableKwaivgiParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKwaivgiParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
