/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedVideoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedVideoRequest{}

// UnifiedVideoRequest struct for UnifiedVideoRequest
type UnifiedVideoRequest struct {
	// Open provider/model slug; model values are not a closed enum.
	Model  string `json:"model"`
	Prompt string `json:"prompt"`
	// Open gptproto scene override; provider-specific legacy scenes are preserved.
	Mode            *string           `json:"mode,omitempty"`
	Duration        *int32            `json:"duration,omitempty"`
	Resolution      *VideoResolution  `json:"resolution,omitempty"`
	AspectRatio     *VideoAspectRatio `json:"aspect_ratio,omitempty"`
	Size            *string           `json:"size,omitempty"`
	FrameImages     []FrameImage      `json:"frame_images,omitempty"`
	InputReferences []ReferenceAsset  `json:"input_references,omitempty"`
	GenerateAudio   NullableBool      `json:"generate_audio,omitempty"`
	Seed            *int32            `json:"seed,omitempty"`
	NegativePrompt  *string           `json:"negative_prompt,omitempty"`
	Provider        *ProviderOptions  `json:"provider,omitempty"`
}

// NewUnifiedVideoRequest instantiates a new UnifiedVideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedVideoRequest(model string, prompt string) *UnifiedVideoRequest {
	this := UnifiedVideoRequest{}
	this.Model = model
	this.Prompt = prompt
	var mode string = "auto"
	this.Mode = &mode
	return &this
}

// NewUnifiedVideoRequestWithDefaults instantiates a new UnifiedVideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedVideoRequestWithDefaults() *UnifiedVideoRequest {
	this := UnifiedVideoRequest{}
	var mode string = "auto"
	this.Mode = &mode
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedVideoRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedVideoRequest) SetModel(v string) {
	o.Model = v
}

// GetPrompt returns the Prompt field value
func (o *UnifiedVideoRequest) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *UnifiedVideoRequest) SetPrompt(v string) {
	o.Prompt = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *UnifiedVideoRequest) SetMode(v string) {
	o.Mode = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *UnifiedVideoRequest) SetDuration(v int32) {
	o.Duration = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetResolution() VideoResolution {
	if o == nil || IsNil(o.Resolution) {
		var ret VideoResolution
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetResolutionOk() (*VideoResolution, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given VideoResolution and assigns it to the Resolution field.
func (o *UnifiedVideoRequest) SetResolution(v VideoResolution) {
	o.Resolution = &v
}

// GetAspectRatio returns the AspectRatio field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetAspectRatio() VideoAspectRatio {
	if o == nil || IsNil(o.AspectRatio) {
		var ret VideoAspectRatio
		return ret
	}
	return *o.AspectRatio
}

// GetAspectRatioOk returns a tuple with the AspectRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetAspectRatioOk() (*VideoAspectRatio, bool) {
	if o == nil || IsNil(o.AspectRatio) {
		return nil, false
	}
	return o.AspectRatio, true
}

// HasAspectRatio returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasAspectRatio() bool {
	if o != nil && !IsNil(o.AspectRatio) {
		return true
	}

	return false
}

// SetAspectRatio gets a reference to the given VideoAspectRatio and assigns it to the AspectRatio field.
func (o *UnifiedVideoRequest) SetAspectRatio(v VideoAspectRatio) {
	o.AspectRatio = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *UnifiedVideoRequest) SetSize(v string) {
	o.Size = &v
}

// GetFrameImages returns the FrameImages field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetFrameImages() []FrameImage {
	if o == nil || IsNil(o.FrameImages) {
		var ret []FrameImage
		return ret
	}
	return o.FrameImages
}

// GetFrameImagesOk returns a tuple with the FrameImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetFrameImagesOk() ([]FrameImage, bool) {
	if o == nil || IsNil(o.FrameImages) {
		return nil, false
	}
	return o.FrameImages, true
}

// HasFrameImages returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasFrameImages() bool {
	if o != nil && !IsNil(o.FrameImages) {
		return true
	}

	return false
}

// SetFrameImages gets a reference to the given []FrameImage and assigns it to the FrameImages field.
func (o *UnifiedVideoRequest) SetFrameImages(v []FrameImage) {
	o.FrameImages = v
}

// GetInputReferences returns the InputReferences field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetInputReferences() []ReferenceAsset {
	if o == nil || IsNil(o.InputReferences) {
		var ret []ReferenceAsset
		return ret
	}
	return o.InputReferences
}

// GetInputReferencesOk returns a tuple with the InputReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetInputReferencesOk() ([]ReferenceAsset, bool) {
	if o == nil || IsNil(o.InputReferences) {
		return nil, false
	}
	return o.InputReferences, true
}

// HasInputReferences returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasInputReferences() bool {
	if o != nil && !IsNil(o.InputReferences) {
		return true
	}

	return false
}

// SetInputReferences gets a reference to the given []ReferenceAsset and assigns it to the InputReferences field.
func (o *UnifiedVideoRequest) SetInputReferences(v []ReferenceAsset) {
	o.InputReferences = v
}

// GetGenerateAudio returns the GenerateAudio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnifiedVideoRequest) GetGenerateAudio() bool {
	if o == nil || IsNil(o.GenerateAudio.Get()) {
		var ret bool
		return ret
	}
	return *o.GenerateAudio.Get()
}

// GetGenerateAudioOk returns a tuple with the GenerateAudio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoRequest) GetGenerateAudioOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.GenerateAudio.Get(), o.GenerateAudio.IsSet()
}

// HasGenerateAudio returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasGenerateAudio() bool {
	if o != nil && o.GenerateAudio.IsSet() {
		return true
	}

	return false
}

// SetGenerateAudio gets a reference to the given NullableBool and assigns it to the GenerateAudio field.
func (o *UnifiedVideoRequest) SetGenerateAudio(v bool) {
	o.GenerateAudio.Set(&v)
}

// SetGenerateAudioNil sets the value for GenerateAudio to be an explicit nil
func (o *UnifiedVideoRequest) SetGenerateAudioNil() {
	o.GenerateAudio.Set(nil)
}

// UnsetGenerateAudio ensures that no value is present for GenerateAudio, not even an explicit nil
func (o *UnifiedVideoRequest) UnsetGenerateAudio() {
	o.GenerateAudio.Unset()
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetSeed() int32 {
	if o == nil || IsNil(o.Seed) {
		var ret int32
		return ret
	}
	return *o.Seed
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetSeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Seed) {
		return nil, false
	}
	return o.Seed, true
}

// HasSeed returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasSeed() bool {
	if o != nil && !IsNil(o.Seed) {
		return true
	}

	return false
}

// SetSeed gets a reference to the given int32 and assigns it to the Seed field.
func (o *UnifiedVideoRequest) SetSeed(v int32) {
	o.Seed = &v
}

// GetNegativePrompt returns the NegativePrompt field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetNegativePrompt() string {
	if o == nil || IsNil(o.NegativePrompt) {
		var ret string
		return ret
	}
	return *o.NegativePrompt
}

// GetNegativePromptOk returns a tuple with the NegativePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetNegativePromptOk() (*string, bool) {
	if o == nil || IsNil(o.NegativePrompt) {
		return nil, false
	}
	return o.NegativePrompt, true
}

// HasNegativePrompt returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasNegativePrompt() bool {
	if o != nil && !IsNil(o.NegativePrompt) {
		return true
	}

	return false
}

// SetNegativePrompt gets a reference to the given string and assigns it to the NegativePrompt field.
func (o *UnifiedVideoRequest) SetNegativePrompt(v string) {
	o.NegativePrompt = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedVideoRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedVideoRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedVideoRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedVideoRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedVideoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["prompt"] = o.Prompt
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	if !IsNil(o.AspectRatio) {
		toSerialize["aspect_ratio"] = o.AspectRatio
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.FrameImages) {
		toSerialize["frame_images"] = o.FrameImages
	}
	if !IsNil(o.InputReferences) {
		toSerialize["input_references"] = o.InputReferences
	}
	if o.GenerateAudio.IsSet() {
		toSerialize["generate_audio"] = o.GenerateAudio.Get()
	}
	if !IsNil(o.Seed) {
		toSerialize["seed"] = o.Seed
	}
	if !IsNil(o.NegativePrompt) {
		toSerialize["negative_prompt"] = o.NegativePrompt
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedVideoRequest struct {
	value *UnifiedVideoRequest
	isSet bool
}

func (v NullableUnifiedVideoRequest) Get() *UnifiedVideoRequest {
	return v.value
}

func (v *NullableUnifiedVideoRequest) Set(val *UnifiedVideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedVideoRequest(val *UnifiedVideoRequest) *NullableUnifiedVideoRequest {
	return &NullableUnifiedVideoRequest{value: val, isSet: true}
}

func (v NullableUnifiedVideoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedVideoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
