/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedErrorResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedErrorResponseError{}

// UnifiedErrorResponseError struct for UnifiedErrorResponseError
type UnifiedErrorResponseError struct {
	Message string `json:"message"`
	Code    int32  `json:"code"`
}

// NewUnifiedErrorResponseError instantiates a new UnifiedErrorResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedErrorResponseError(message string, code int32) *UnifiedErrorResponseError {
	this := UnifiedErrorResponseError{}
	this.Message = message
	this.Code = code
	return &this
}

// NewUnifiedErrorResponseErrorWithDefaults instantiates a new UnifiedErrorResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedErrorResponseErrorWithDefaults() *UnifiedErrorResponseError {
	this := UnifiedErrorResponseError{}
	return &this
}

// GetMessage returns the Message field value
func (o *UnifiedErrorResponseError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UnifiedErrorResponseError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UnifiedErrorResponseError) SetMessage(v string) {
	o.Message = v
}

// GetCode returns the Code field value
func (o *UnifiedErrorResponseError) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *UnifiedErrorResponseError) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *UnifiedErrorResponseError) SetCode(v int32) {
	o.Code = v
}

func (o UnifiedErrorResponseError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedErrorResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

type NullableUnifiedErrorResponseError struct {
	value *UnifiedErrorResponseError
	isSet bool
}

func (v NullableUnifiedErrorResponseError) Get() *UnifiedErrorResponseError {
	return v.value
}

func (v *NullableUnifiedErrorResponseError) Set(val *UnifiedErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedErrorResponseError(val *UnifiedErrorResponseError) *NullableUnifiedErrorResponseError {
	return &NullableUnifiedErrorResponseError{value: val, isSet: true}
}

func (v NullableUnifiedErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
