/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ImageUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageUrl{}

// ImageUrl struct for ImageUrl
type ImageUrl struct {
	Url string `json:"url"`
}

// NewImageUrl instantiates a new ImageUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUrl(url string) *ImageUrl {
	this := ImageUrl{}
	this.Url = url
	return &this
}

// NewImageUrlWithDefaults instantiates a new ImageUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUrlWithDefaults() *ImageUrl {
	this := ImageUrl{}
	return &this
}

// GetUrl returns the Url field value
func (o *ImageUrl) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ImageUrl) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ImageUrl) SetUrl(v string) {
	o.Url = v
}

func (o ImageUrl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

type NullableImageUrl struct {
	value *ImageUrl
	isSet bool
}

func (v NullableImageUrl) Get() *ImageUrl {
	return v.value
}

func (v *NullableImageUrl) Set(val *ImageUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUrl(val *ImageUrl) *NullableImageUrl {
	return &NullableImageUrl{value: val, isSet: true}
}

func (v NullableImageUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
