/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
	"fmt"
)

// ImageAspectRatio the model 'ImageAspectRatio'
type ImageAspectRatio string

// List of ImageAspectRatio
const (
	IMAGEASPECTRATIO_RATIO_1_1    ImageAspectRatio = "1:1"
	IMAGEASPECTRATIO_RATIO_1_2    ImageAspectRatio = "1:2"
	IMAGEASPECTRATIO_RATIO_1_4    ImageAspectRatio = "1:4"
	IMAGEASPECTRATIO_RATIO_1_8    ImageAspectRatio = "1:8"
	IMAGEASPECTRATIO_RATIO_2_1    ImageAspectRatio = "2:1"
	IMAGEASPECTRATIO_RATIO_2_3    ImageAspectRatio = "2:3"
	IMAGEASPECTRATIO_RATIO_3_2    ImageAspectRatio = "3:2"
	IMAGEASPECTRATIO_RATIO_3_4    ImageAspectRatio = "3:4"
	IMAGEASPECTRATIO_RATIO_4_1    ImageAspectRatio = "4:1"
	IMAGEASPECTRATIO_RATIO_4_3    ImageAspectRatio = "4:3"
	IMAGEASPECTRATIO_RATIO_4_5    ImageAspectRatio = "4:5"
	IMAGEASPECTRATIO_RATIO_5_4    ImageAspectRatio = "5:4"
	IMAGEASPECTRATIO_RATIO_8_1    ImageAspectRatio = "8:1"
	IMAGEASPECTRATIO_RATIO_9_16   ImageAspectRatio = "9:16"
	IMAGEASPECTRATIO_RATIO_16_9   ImageAspectRatio = "16:9"
	IMAGEASPECTRATIO_RATIO_9_19_5 ImageAspectRatio = "9:19.5"
	IMAGEASPECTRATIO_RATIO_19_5_9 ImageAspectRatio = "19.5:9"
	IMAGEASPECTRATIO_RATIO_9_20   ImageAspectRatio = "9:20"
	IMAGEASPECTRATIO_RATIO_20_9   ImageAspectRatio = "20:9"
	IMAGEASPECTRATIO_RATIO_9_21   ImageAspectRatio = "9:21"
	IMAGEASPECTRATIO_RATIO_21_9   ImageAspectRatio = "21:9"
	IMAGEASPECTRATIO_AUTO         ImageAspectRatio = "auto"
)

// All allowed values of ImageAspectRatio enum
var AllowedImageAspectRatioEnumValues = []ImageAspectRatio{
	"1:1",
	"1:2",
	"1:4",
	"1:8",
	"2:1",
	"2:3",
	"3:2",
	"3:4",
	"4:1",
	"4:3",
	"4:5",
	"5:4",
	"8:1",
	"9:16",
	"16:9",
	"9:19.5",
	"19.5:9",
	"9:20",
	"20:9",
	"9:21",
	"21:9",
	"auto",
}

func (v *ImageAspectRatio) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ImageAspectRatio(value)
	for _, existing := range AllowedImageAspectRatioEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ImageAspectRatio", value)
}

// NewImageAspectRatioFromValue returns a pointer to a valid ImageAspectRatio
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewImageAspectRatioFromValue(v string) (*ImageAspectRatio, error) {
	ev := ImageAspectRatio(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ImageAspectRatio: valid values are %v", v, AllowedImageAspectRatioEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ImageAspectRatio) IsValid() bool {
	for _, existing := range AllowedImageAspectRatioEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ImageAspectRatio value
func (v ImageAspectRatio) Ptr() *ImageAspectRatio {
	return &v
}

type NullableImageAspectRatio struct {
	value *ImageAspectRatio
	isSet bool
}

func (v NullableImageAspectRatio) Get() *ImageAspectRatio {
	return v.value
}

func (v *NullableImageAspectRatio) Set(val *ImageAspectRatio) {
	v.value = val
	v.isSet = true
}

func (v NullableImageAspectRatio) IsSet() bool {
	return v.isSet
}

func (v *NullableImageAspectRatio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageAspectRatio(val *ImageAspectRatio) *NullableImageAspectRatio {
	return &NullableImageAspectRatio{value: val, isSet: true}
}

func (v NullableImageAspectRatio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageAspectRatio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
