/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ProviderOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderOptions{}

// ProviderOptions Only options is public in this release; routing controls are intentionally hidden.
type ProviderOptions struct {
	Options *ProviderOptionsOptions `json:"options,omitempty"`
}

// NewProviderOptions instantiates a new ProviderOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderOptions() *ProviderOptions {
	this := ProviderOptions{}
	return &this
}

// NewProviderOptionsWithDefaults instantiates a new ProviderOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderOptionsWithDefaults() *ProviderOptions {
	this := ProviderOptions{}
	return &this
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *ProviderOptions) GetOptions() ProviderOptionsOptions {
	if o == nil || IsNil(o.Options) {
		var ret ProviderOptionsOptions
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOptions) GetOptionsOk() (*ProviderOptionsOptions, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *ProviderOptions) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given ProviderOptionsOptions and assigns it to the Options field.
func (o *ProviderOptions) SetOptions(v ProviderOptionsOptions) {
	o.Options = &v
}

func (o ProviderOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableProviderOptions struct {
	value *ProviderOptions
	isSet bool
}

func (v NullableProviderOptions) Get() *ProviderOptions {
	return v.value
}

func (v *NullableProviderOptions) Set(val *ProviderOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderOptions(val *ProviderOptions) *NullableProviderOptions {
	return &NullableProviderOptions{value: val, isSet: true}
}

func (v NullableProviderOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
