/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the MinimaxProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MinimaxProviderOptionParameters{}

// MinimaxProviderOptionParameters struct for MinimaxProviderOptionParameters
type MinimaxProviderOptionParameters struct {
	EnablePromptExpansion *bool    `json:"enable_prompt_expansion,omitempty"`
	GoFast                *bool    `json:"go_fast,omitempty"`
	Emotion               *string  `json:"emotion,omitempty"`
	EnableBase64Output    *bool    `json:"enable_base64_output,omitempty"`
	EnableSyncMode        *bool    `json:"enable_sync_mode,omitempty"`
	EnglishNormalization  *bool    `json:"english_normalization,omitempty"`
	Pitch                 *int32   `json:"pitch,omitempty"`
	Volume                *float32 `json:"volume,omitempty"`
	LanguageBoost         *string  `json:"language_boost,omitempty"`
}

// NewMinimaxProviderOptionParameters instantiates a new MinimaxProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinimaxProviderOptionParameters() *MinimaxProviderOptionParameters {
	this := MinimaxProviderOptionParameters{}
	return &this
}

// NewMinimaxProviderOptionParametersWithDefaults instantiates a new MinimaxProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinimaxProviderOptionParametersWithDefaults() *MinimaxProviderOptionParameters {
	this := MinimaxProviderOptionParameters{}
	return &this
}

// GetEnablePromptExpansion returns the EnablePromptExpansion field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetEnablePromptExpansion() bool {
	if o == nil || IsNil(o.EnablePromptExpansion) {
		var ret bool
		return ret
	}
	return *o.EnablePromptExpansion
}

// GetEnablePromptExpansionOk returns a tuple with the EnablePromptExpansion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetEnablePromptExpansionOk() (*bool, bool) {
	if o == nil || IsNil(o.EnablePromptExpansion) {
		return nil, false
	}
	return o.EnablePromptExpansion, true
}

// HasEnablePromptExpansion returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasEnablePromptExpansion() bool {
	if o != nil && !IsNil(o.EnablePromptExpansion) {
		return true
	}

	return false
}

// SetEnablePromptExpansion gets a reference to the given bool and assigns it to the EnablePromptExpansion field.
func (o *MinimaxProviderOptionParameters) SetEnablePromptExpansion(v bool) {
	o.EnablePromptExpansion = &v
}

// GetGoFast returns the GoFast field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetGoFast() bool {
	if o == nil || IsNil(o.GoFast) {
		var ret bool
		return ret
	}
	return *o.GoFast
}

// GetGoFastOk returns a tuple with the GoFast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetGoFastOk() (*bool, bool) {
	if o == nil || IsNil(o.GoFast) {
		return nil, false
	}
	return o.GoFast, true
}

// HasGoFast returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasGoFast() bool {
	if o != nil && !IsNil(o.GoFast) {
		return true
	}

	return false
}

// SetGoFast gets a reference to the given bool and assigns it to the GoFast field.
func (o *MinimaxProviderOptionParameters) SetGoFast(v bool) {
	o.GoFast = &v
}

// GetEmotion returns the Emotion field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetEmotion() string {
	if o == nil || IsNil(o.Emotion) {
		var ret string
		return ret
	}
	return *o.Emotion
}

// GetEmotionOk returns a tuple with the Emotion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetEmotionOk() (*string, bool) {
	if o == nil || IsNil(o.Emotion) {
		return nil, false
	}
	return o.Emotion, true
}

// HasEmotion returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasEmotion() bool {
	if o != nil && !IsNil(o.Emotion) {
		return true
	}

	return false
}

// SetEmotion gets a reference to the given string and assigns it to the Emotion field.
func (o *MinimaxProviderOptionParameters) SetEmotion(v string) {
	o.Emotion = &v
}

// GetEnableBase64Output returns the EnableBase64Output field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetEnableBase64Output() bool {
	if o == nil || IsNil(o.EnableBase64Output) {
		var ret bool
		return ret
	}
	return *o.EnableBase64Output
}

// GetEnableBase64OutputOk returns a tuple with the EnableBase64Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetEnableBase64OutputOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableBase64Output) {
		return nil, false
	}
	return o.EnableBase64Output, true
}

// HasEnableBase64Output returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasEnableBase64Output() bool {
	if o != nil && !IsNil(o.EnableBase64Output) {
		return true
	}

	return false
}

// SetEnableBase64Output gets a reference to the given bool and assigns it to the EnableBase64Output field.
func (o *MinimaxProviderOptionParameters) SetEnableBase64Output(v bool) {
	o.EnableBase64Output = &v
}

// GetEnableSyncMode returns the EnableSyncMode field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetEnableSyncMode() bool {
	if o == nil || IsNil(o.EnableSyncMode) {
		var ret bool
		return ret
	}
	return *o.EnableSyncMode
}

// GetEnableSyncModeOk returns a tuple with the EnableSyncMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetEnableSyncModeOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSyncMode) {
		return nil, false
	}
	return o.EnableSyncMode, true
}

// HasEnableSyncMode returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasEnableSyncMode() bool {
	if o != nil && !IsNil(o.EnableSyncMode) {
		return true
	}

	return false
}

// SetEnableSyncMode gets a reference to the given bool and assigns it to the EnableSyncMode field.
func (o *MinimaxProviderOptionParameters) SetEnableSyncMode(v bool) {
	o.EnableSyncMode = &v
}

// GetEnglishNormalization returns the EnglishNormalization field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetEnglishNormalization() bool {
	if o == nil || IsNil(o.EnglishNormalization) {
		var ret bool
		return ret
	}
	return *o.EnglishNormalization
}

// GetEnglishNormalizationOk returns a tuple with the EnglishNormalization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetEnglishNormalizationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnglishNormalization) {
		return nil, false
	}
	return o.EnglishNormalization, true
}

// HasEnglishNormalization returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasEnglishNormalization() bool {
	if o != nil && !IsNil(o.EnglishNormalization) {
		return true
	}

	return false
}

// SetEnglishNormalization gets a reference to the given bool and assigns it to the EnglishNormalization field.
func (o *MinimaxProviderOptionParameters) SetEnglishNormalization(v bool) {
	o.EnglishNormalization = &v
}

// GetPitch returns the Pitch field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetPitch() int32 {
	if o == nil || IsNil(o.Pitch) {
		var ret int32
		return ret
	}
	return *o.Pitch
}

// GetPitchOk returns a tuple with the Pitch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetPitchOk() (*int32, bool) {
	if o == nil || IsNil(o.Pitch) {
		return nil, false
	}
	return o.Pitch, true
}

// HasPitch returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasPitch() bool {
	if o != nil && !IsNil(o.Pitch) {
		return true
	}

	return false
}

// SetPitch gets a reference to the given int32 and assigns it to the Pitch field.
func (o *MinimaxProviderOptionParameters) SetPitch(v int32) {
	o.Pitch = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetVolume() float32 {
	if o == nil || IsNil(o.Volume) {
		var ret float32
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetVolumeOk() (*float32, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float32 and assigns it to the Volume field.
func (o *MinimaxProviderOptionParameters) SetVolume(v float32) {
	o.Volume = &v
}

// GetLanguageBoost returns the LanguageBoost field value if set, zero value otherwise.
func (o *MinimaxProviderOptionParameters) GetLanguageBoost() string {
	if o == nil || IsNil(o.LanguageBoost) {
		var ret string
		return ret
	}
	return *o.LanguageBoost
}

// GetLanguageBoostOk returns a tuple with the LanguageBoost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimaxProviderOptionParameters) GetLanguageBoostOk() (*string, bool) {
	if o == nil || IsNil(o.LanguageBoost) {
		return nil, false
	}
	return o.LanguageBoost, true
}

// HasLanguageBoost returns a boolean if a field has been set.
func (o *MinimaxProviderOptionParameters) HasLanguageBoost() bool {
	if o != nil && !IsNil(o.LanguageBoost) {
		return true
	}

	return false
}

// SetLanguageBoost gets a reference to the given string and assigns it to the LanguageBoost field.
func (o *MinimaxProviderOptionParameters) SetLanguageBoost(v string) {
	o.LanguageBoost = &v
}

func (o MinimaxProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MinimaxProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnablePromptExpansion) {
		toSerialize["enable_prompt_expansion"] = o.EnablePromptExpansion
	}
	if !IsNil(o.GoFast) {
		toSerialize["go_fast"] = o.GoFast
	}
	if !IsNil(o.Emotion) {
		toSerialize["emotion"] = o.Emotion
	}
	if !IsNil(o.EnableBase64Output) {
		toSerialize["enable_base64_output"] = o.EnableBase64Output
	}
	if !IsNil(o.EnableSyncMode) {
		toSerialize["enable_sync_mode"] = o.EnableSyncMode
	}
	if !IsNil(o.EnglishNormalization) {
		toSerialize["english_normalization"] = o.EnglishNormalization
	}
	if !IsNil(o.Pitch) {
		toSerialize["pitch"] = o.Pitch
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.LanguageBoost) {
		toSerialize["language_boost"] = o.LanguageBoost
	}
	return toSerialize, nil
}

type NullableMinimaxProviderOptionParameters struct {
	value *MinimaxProviderOptionParameters
	isSet bool
}

func (v NullableMinimaxProviderOptionParameters) Get() *MinimaxProviderOptionParameters {
	return v.value
}

func (v *NullableMinimaxProviderOptionParameters) Set(val *MinimaxProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableMinimaxProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableMinimaxProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinimaxProviderOptionParameters(val *MinimaxProviderOptionParameters) *NullableMinimaxProviderOptionParameters {
	return &NullableMinimaxProviderOptionParameters{value: val, isSet: true}
}

func (v NullableMinimaxProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinimaxProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
