/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the GoogleProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleProviderOptionParameters{}

// GoogleProviderOptionParameters struct for GoogleProviderOptionParameters
type GoogleProviderOptionParameters struct {
	EnhancePrompt  *bool `json:"enhance_prompt,omitempty"`
	EnableUpsample *bool `json:"enable_upsample,omitempty"`
}

// NewGoogleProviderOptionParameters instantiates a new GoogleProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleProviderOptionParameters() *GoogleProviderOptionParameters {
	this := GoogleProviderOptionParameters{}
	return &this
}

// NewGoogleProviderOptionParametersWithDefaults instantiates a new GoogleProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleProviderOptionParametersWithDefaults() *GoogleProviderOptionParameters {
	this := GoogleProviderOptionParameters{}
	return &this
}

// GetEnhancePrompt returns the EnhancePrompt field value if set, zero value otherwise.
func (o *GoogleProviderOptionParameters) GetEnhancePrompt() bool {
	if o == nil || IsNil(o.EnhancePrompt) {
		var ret bool
		return ret
	}
	return *o.EnhancePrompt
}

// GetEnhancePromptOk returns a tuple with the EnhancePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleProviderOptionParameters) GetEnhancePromptOk() (*bool, bool) {
	if o == nil || IsNil(o.EnhancePrompt) {
		return nil, false
	}
	return o.EnhancePrompt, true
}

// HasEnhancePrompt returns a boolean if a field has been set.
func (o *GoogleProviderOptionParameters) HasEnhancePrompt() bool {
	if o != nil && !IsNil(o.EnhancePrompt) {
		return true
	}

	return false
}

// SetEnhancePrompt gets a reference to the given bool and assigns it to the EnhancePrompt field.
func (o *GoogleProviderOptionParameters) SetEnhancePrompt(v bool) {
	o.EnhancePrompt = &v
}

// GetEnableUpsample returns the EnableUpsample field value if set, zero value otherwise.
func (o *GoogleProviderOptionParameters) GetEnableUpsample() bool {
	if o == nil || IsNil(o.EnableUpsample) {
		var ret bool
		return ret
	}
	return *o.EnableUpsample
}

// GetEnableUpsampleOk returns a tuple with the EnableUpsample field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleProviderOptionParameters) GetEnableUpsampleOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableUpsample) {
		return nil, false
	}
	return o.EnableUpsample, true
}

// HasEnableUpsample returns a boolean if a field has been set.
func (o *GoogleProviderOptionParameters) HasEnableUpsample() bool {
	if o != nil && !IsNil(o.EnableUpsample) {
		return true
	}

	return false
}

// SetEnableUpsample gets a reference to the given bool and assigns it to the EnableUpsample field.
func (o *GoogleProviderOptionParameters) SetEnableUpsample(v bool) {
	o.EnableUpsample = &v
}

func (o GoogleProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnhancePrompt) {
		toSerialize["enhance_prompt"] = o.EnhancePrompt
	}
	if !IsNil(o.EnableUpsample) {
		toSerialize["enable_upsample"] = o.EnableUpsample
	}
	return toSerialize, nil
}

type NullableGoogleProviderOptionParameters struct {
	value *GoogleProviderOptionParameters
	isSet bool
}

func (v NullableGoogleProviderOptionParameters) Get() *GoogleProviderOptionParameters {
	return v.value
}

func (v *NullableGoogleProviderOptionParameters) Set(val *GoogleProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleProviderOptionParameters(val *GoogleProviderOptionParameters) *NullableGoogleProviderOptionParameters {
	return &NullableGoogleProviderOptionParameters{value: val, isSet: true}
}

func (v NullableGoogleProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
