/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
	"fmt"
)

// VideoAspectRatio auto is a retained Vidu extension.
type VideoAspectRatio string

// List of VideoAspectRatio
const (
	VIDEOASPECTRATIO_LANDSCAPE_16_9 VideoAspectRatio = "16:9"
	VIDEOASPECTRATIO_PORTRAIT_9_16  VideoAspectRatio = "9:16"
	VIDEOASPECTRATIO_SQUARE_1_1     VideoAspectRatio = "1:1"
	VIDEOASPECTRATIO_LANDSCAPE_4_3  VideoAspectRatio = "4:3"
	VIDEOASPECTRATIO_PORTRAIT_3_4   VideoAspectRatio = "3:4"
	VIDEOASPECTRATIO_LANDSCAPE_3_2  VideoAspectRatio = "3:2"
	VIDEOASPECTRATIO_PORTRAIT_2_3   VideoAspectRatio = "2:3"
	VIDEOASPECTRATIO_ULTRAWIDE_21_9 VideoAspectRatio = "21:9"
	VIDEOASPECTRATIO_TALL_9_21      VideoAspectRatio = "9:21"
	VIDEOASPECTRATIO_AUTO           VideoAspectRatio = "auto"
)

// All allowed values of VideoAspectRatio enum
var AllowedVideoAspectRatioEnumValues = []VideoAspectRatio{
	"16:9",
	"9:16",
	"1:1",
	"4:3",
	"3:4",
	"3:2",
	"2:3",
	"21:9",
	"9:21",
	"auto",
}

func (v *VideoAspectRatio) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VideoAspectRatio(value)
	for _, existing := range AllowedVideoAspectRatioEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VideoAspectRatio", value)
}

// NewVideoAspectRatioFromValue returns a pointer to a valid VideoAspectRatio
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVideoAspectRatioFromValue(v string) (*VideoAspectRatio, error) {
	ev := VideoAspectRatio(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VideoAspectRatio: valid values are %v", v, AllowedVideoAspectRatioEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VideoAspectRatio) IsValid() bool {
	for _, existing := range AllowedVideoAspectRatioEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VideoAspectRatio value
func (v VideoAspectRatio) Ptr() *VideoAspectRatio {
	return &v
}

type NullableVideoAspectRatio struct {
	value *VideoAspectRatio
	isSet bool
}

func (v NullableVideoAspectRatio) Get() *VideoAspectRatio {
	return v.value
}

func (v *NullableVideoAspectRatio) Set(val *VideoAspectRatio) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoAspectRatio) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoAspectRatio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoAspectRatio(val *VideoAspectRatio) *NullableVideoAspectRatio {
	return &NullableVideoAspectRatio{value: val, isSet: true}
}

func (v NullableVideoAspectRatio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoAspectRatio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
