/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ReferenceAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceAsset{}

// ReferenceAsset struct for ReferenceAsset
type ReferenceAsset struct {
	Type     string   `json:"type"`
	ImageUrl ImageUrl `json:"image_url"`
}

// NewReferenceAsset instantiates a new ReferenceAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceAsset(type_ string, imageUrl ImageUrl) *ReferenceAsset {
	this := ReferenceAsset{}
	this.Type = type_
	this.ImageUrl = imageUrl
	return &this
}

// NewReferenceAssetWithDefaults instantiates a new ReferenceAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceAssetWithDefaults() *ReferenceAsset {
	this := ReferenceAsset{}
	return &this
}

// GetType returns the Type field value
func (o *ReferenceAsset) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReferenceAsset) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReferenceAsset) SetType(v string) {
	o.Type = v
}

// GetImageUrl returns the ImageUrl field value
func (o *ReferenceAsset) GetImageUrl() ImageUrl {
	if o == nil {
		var ret ImageUrl
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *ReferenceAsset) GetImageUrlOk() (*ImageUrl, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *ReferenceAsset) SetImageUrl(v ImageUrl) {
	o.ImageUrl = v
}

func (o ReferenceAsset) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["image_url"] = o.ImageUrl
	return toSerialize, nil
}

type NullableReferenceAsset struct {
	value *ReferenceAsset
	isSet bool
}

func (v NullableReferenceAsset) Get() *ReferenceAsset {
	return v.value
}

func (v *NullableReferenceAsset) Set(val *ReferenceAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceAsset(val *ReferenceAsset) *NullableReferenceAsset {
	return &NullableReferenceAsset{value: val, isSet: true}
}

func (v NullableReferenceAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
