/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the SoraReverseProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoraReverseProviderOption{}

// SoraReverseProviderOption struct for SoraReverseProviderOption
type SoraReverseProviderOption struct {
	Parameters SoraReverseProviderOptionParameters `json:"parameters"`
}

// NewSoraReverseProviderOption instantiates a new SoraReverseProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoraReverseProviderOption(parameters SoraReverseProviderOptionParameters) *SoraReverseProviderOption {
	this := SoraReverseProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewSoraReverseProviderOptionWithDefaults instantiates a new SoraReverseProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoraReverseProviderOptionWithDefaults() *SoraReverseProviderOption {
	this := SoraReverseProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *SoraReverseProviderOption) GetParameters() SoraReverseProviderOptionParameters {
	if o == nil {
		var ret SoraReverseProviderOptionParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *SoraReverseProviderOption) GetParametersOk() (*SoraReverseProviderOptionParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *SoraReverseProviderOption) SetParameters(v SoraReverseProviderOptionParameters) {
	o.Parameters = v
}

func (o SoraReverseProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoraReverseProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableSoraReverseProviderOption struct {
	value *SoraReverseProviderOption
	isSet bool
}

func (v NullableSoraReverseProviderOption) Get() *SoraReverseProviderOption {
	return v.value
}

func (v *NullableSoraReverseProviderOption) Set(val *SoraReverseProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableSoraReverseProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableSoraReverseProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoraReverseProviderOption(val *SoraReverseProviderOption) *NullableSoraReverseProviderOption {
	return &NullableSoraReverseProviderOption{value: val, isSet: true}
}

func (v NullableSoraReverseProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoraReverseProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
