/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedVoiceCloneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedVoiceCloneRequest{}

// UnifiedVoiceCloneRequest struct for UnifiedVoiceCloneRequest
type UnifiedVoiceCloneRequest struct {
	Model                   string           `json:"model"`
	Audio                   string           `json:"audio"`
	Text                    *string          `json:"text,omitempty"`
	CustomVoiceId           *string          `json:"custom_voice_id,omitempty"`
	Accuracy                *float64         `json:"accuracy,omitempty"`
	NeedNoiseReduction      *bool            `json:"need_noise_reduction,omitempty"`
	NeedVolumeNormalization *bool            `json:"need_volume_normalization,omitempty"`
	Provider                *ProviderOptions `json:"provider,omitempty"`
}

// NewUnifiedVoiceCloneRequest instantiates a new UnifiedVoiceCloneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedVoiceCloneRequest(model string, audio string) *UnifiedVoiceCloneRequest {
	this := UnifiedVoiceCloneRequest{}
	this.Model = model
	this.Audio = audio
	return &this
}

// NewUnifiedVoiceCloneRequestWithDefaults instantiates a new UnifiedVoiceCloneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedVoiceCloneRequestWithDefaults() *UnifiedVoiceCloneRequest {
	this := UnifiedVoiceCloneRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedVoiceCloneRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedVoiceCloneRequest) SetModel(v string) {
	o.Model = v
}

// GetAudio returns the Audio field value
func (o *UnifiedVoiceCloneRequest) GetAudio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audio
}

// GetAudioOk returns a tuple with the Audio field value
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetAudioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audio, true
}

// SetAudio sets field value
func (o *UnifiedVoiceCloneRequest) SetAudio(v string) {
	o.Audio = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *UnifiedVoiceCloneRequest) SetText(v string) {
	o.Text = &v
}

// GetCustomVoiceId returns the CustomVoiceId field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetCustomVoiceId() string {
	if o == nil || IsNil(o.CustomVoiceId) {
		var ret string
		return ret
	}
	return *o.CustomVoiceId
}

// GetCustomVoiceIdOk returns a tuple with the CustomVoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetCustomVoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomVoiceId) {
		return nil, false
	}
	return o.CustomVoiceId, true
}

// HasCustomVoiceId returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasCustomVoiceId() bool {
	if o != nil && !IsNil(o.CustomVoiceId) {
		return true
	}

	return false
}

// SetCustomVoiceId gets a reference to the given string and assigns it to the CustomVoiceId field.
func (o *UnifiedVoiceCloneRequest) SetCustomVoiceId(v string) {
	o.CustomVoiceId = &v
}

// GetAccuracy returns the Accuracy field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetAccuracy() float64 {
	if o == nil || IsNil(o.Accuracy) {
		var ret float64
		return ret
	}
	return *o.Accuracy
}

// GetAccuracyOk returns a tuple with the Accuracy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetAccuracyOk() (*float64, bool) {
	if o == nil || IsNil(o.Accuracy) {
		return nil, false
	}
	return o.Accuracy, true
}

// HasAccuracy returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasAccuracy() bool {
	if o != nil && !IsNil(o.Accuracy) {
		return true
	}

	return false
}

// SetAccuracy gets a reference to the given float64 and assigns it to the Accuracy field.
func (o *UnifiedVoiceCloneRequest) SetAccuracy(v float64) {
	o.Accuracy = &v
}

// GetNeedNoiseReduction returns the NeedNoiseReduction field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetNeedNoiseReduction() bool {
	if o == nil || IsNil(o.NeedNoiseReduction) {
		var ret bool
		return ret
	}
	return *o.NeedNoiseReduction
}

// GetNeedNoiseReductionOk returns a tuple with the NeedNoiseReduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetNeedNoiseReductionOk() (*bool, bool) {
	if o == nil || IsNil(o.NeedNoiseReduction) {
		return nil, false
	}
	return o.NeedNoiseReduction, true
}

// HasNeedNoiseReduction returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasNeedNoiseReduction() bool {
	if o != nil && !IsNil(o.NeedNoiseReduction) {
		return true
	}

	return false
}

// SetNeedNoiseReduction gets a reference to the given bool and assigns it to the NeedNoiseReduction field.
func (o *UnifiedVoiceCloneRequest) SetNeedNoiseReduction(v bool) {
	o.NeedNoiseReduction = &v
}

// GetNeedVolumeNormalization returns the NeedVolumeNormalization field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetNeedVolumeNormalization() bool {
	if o == nil || IsNil(o.NeedVolumeNormalization) {
		var ret bool
		return ret
	}
	return *o.NeedVolumeNormalization
}

// GetNeedVolumeNormalizationOk returns a tuple with the NeedVolumeNormalization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetNeedVolumeNormalizationOk() (*bool, bool) {
	if o == nil || IsNil(o.NeedVolumeNormalization) {
		return nil, false
	}
	return o.NeedVolumeNormalization, true
}

// HasNeedVolumeNormalization returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasNeedVolumeNormalization() bool {
	if o != nil && !IsNil(o.NeedVolumeNormalization) {
		return true
	}

	return false
}

// SetNeedVolumeNormalization gets a reference to the given bool and assigns it to the NeedVolumeNormalization field.
func (o *UnifiedVoiceCloneRequest) SetNeedVolumeNormalization(v bool) {
	o.NeedVolumeNormalization = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedVoiceCloneRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVoiceCloneRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedVoiceCloneRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedVoiceCloneRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedVoiceCloneRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedVoiceCloneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["audio"] = o.Audio
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.CustomVoiceId) {
		toSerialize["custom_voice_id"] = o.CustomVoiceId
	}
	if !IsNil(o.Accuracy) {
		toSerialize["accuracy"] = o.Accuracy
	}
	if !IsNil(o.NeedNoiseReduction) {
		toSerialize["need_noise_reduction"] = o.NeedNoiseReduction
	}
	if !IsNil(o.NeedVolumeNormalization) {
		toSerialize["need_volume_normalization"] = o.NeedVolumeNormalization
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedVoiceCloneRequest struct {
	value *UnifiedVoiceCloneRequest
	isSet bool
}

func (v NullableUnifiedVoiceCloneRequest) Get() *UnifiedVoiceCloneRequest {
	return v.value
}

func (v *NullableUnifiedVoiceCloneRequest) Set(val *UnifiedVoiceCloneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedVoiceCloneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedVoiceCloneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedVoiceCloneRequest(val *UnifiedVoiceCloneRequest) *NullableUnifiedVoiceCloneRequest {
	return &NullableUnifiedVoiceCloneRequest{value: val, isSet: true}
}

func (v NullableUnifiedVoiceCloneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedVoiceCloneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
