/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ImageReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageReference{}

// ImageReference struct for ImageReference
type ImageReference struct {
	Type     string   `json:"type"`
	ImageUrl ImageUrl `json:"image_url"`
}

// NewImageReference instantiates a new ImageReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageReference(type_ string, imageUrl ImageUrl) *ImageReference {
	this := ImageReference{}
	this.Type = type_
	this.ImageUrl = imageUrl
	return &this
}

// NewImageReferenceWithDefaults instantiates a new ImageReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageReferenceWithDefaults() *ImageReference {
	this := ImageReference{}
	return &this
}

// GetType returns the Type field value
func (o *ImageReference) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ImageReference) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ImageReference) SetType(v string) {
	o.Type = v
}

// GetImageUrl returns the ImageUrl field value
func (o *ImageReference) GetImageUrl() ImageUrl {
	if o == nil {
		var ret ImageUrl
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *ImageReference) GetImageUrlOk() (*ImageUrl, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *ImageReference) SetImageUrl(v ImageUrl) {
	o.ImageUrl = v
}

func (o ImageReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["image_url"] = o.ImageUrl
	return toSerialize, nil
}

type NullableImageReference struct {
	value *ImageReference
	isSet bool
}

func (v NullableImageReference) Get() *ImageReference {
	return v.value
}

func (v *NullableImageReference) Set(val *ImageReference) {
	v.value = val
	v.isSet = true
}

func (v NullableImageReference) IsSet() bool {
	return v.isSet
}

func (v *NullableImageReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageReference(val *ImageReference) *NullableImageReference {
	return &NullableImageReference{value: val, isSet: true}
}

func (v NullableImageReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
