/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedErrorResponse{}

// UnifiedErrorResponse struct for UnifiedErrorResponse
type UnifiedErrorResponse struct {
	Error UnifiedErrorResponseError `json:"error"`
}

// NewUnifiedErrorResponse instantiates a new UnifiedErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedErrorResponse(error_ UnifiedErrorResponseError) *UnifiedErrorResponse {
	this := UnifiedErrorResponse{}
	this.Error = error_
	return &this
}

// NewUnifiedErrorResponseWithDefaults instantiates a new UnifiedErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedErrorResponseWithDefaults() *UnifiedErrorResponse {
	this := UnifiedErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *UnifiedErrorResponse) GetError() UnifiedErrorResponseError {
	if o == nil {
		var ret UnifiedErrorResponseError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *UnifiedErrorResponse) GetErrorOk() (*UnifiedErrorResponseError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *UnifiedErrorResponse) SetError(v UnifiedErrorResponseError) {
	o.Error = v
}

func (o UnifiedErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

type NullableUnifiedErrorResponse struct {
	value *UnifiedErrorResponse
	isSet bool
}

func (v NullableUnifiedErrorResponse) Get() *UnifiedErrorResponse {
	return v.value
}

func (v *NullableUnifiedErrorResponse) Set(val *UnifiedErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedErrorResponse(val *UnifiedErrorResponse) *NullableUnifiedErrorResponse {
	return &NullableUnifiedErrorResponse{value: val, isSet: true}
}

func (v NullableUnifiedErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
