/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedLipSyncRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedLipSyncRequest{}

// UnifiedLipSyncRequest struct for UnifiedLipSyncRequest
type UnifiedLipSyncRequest struct {
	Model    string           `json:"model"`
	Video    string           `json:"video"`
	Audio    string           `json:"audio"`
	Provider *ProviderOptions `json:"provider,omitempty"`
}

// NewUnifiedLipSyncRequest instantiates a new UnifiedLipSyncRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedLipSyncRequest(model string, video string, audio string) *UnifiedLipSyncRequest {
	this := UnifiedLipSyncRequest{}
	this.Model = model
	this.Video = video
	this.Audio = audio
	return &this
}

// NewUnifiedLipSyncRequestWithDefaults instantiates a new UnifiedLipSyncRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedLipSyncRequestWithDefaults() *UnifiedLipSyncRequest {
	this := UnifiedLipSyncRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedLipSyncRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedLipSyncRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedLipSyncRequest) SetModel(v string) {
	o.Model = v
}

// GetVideo returns the Video field value
func (o *UnifiedLipSyncRequest) GetVideo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Video
}

// GetVideoOk returns a tuple with the Video field value
// and a boolean to check if the value has been set.
func (o *UnifiedLipSyncRequest) GetVideoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Video, true
}

// SetVideo sets field value
func (o *UnifiedLipSyncRequest) SetVideo(v string) {
	o.Video = v
}

// GetAudio returns the Audio field value
func (o *UnifiedLipSyncRequest) GetAudio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audio
}

// GetAudioOk returns a tuple with the Audio field value
// and a boolean to check if the value has been set.
func (o *UnifiedLipSyncRequest) GetAudioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audio, true
}

// SetAudio sets field value
func (o *UnifiedLipSyncRequest) SetAudio(v string) {
	o.Audio = v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedLipSyncRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedLipSyncRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedLipSyncRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedLipSyncRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedLipSyncRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedLipSyncRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["video"] = o.Video
	toSerialize["audio"] = o.Audio
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedLipSyncRequest struct {
	value *UnifiedLipSyncRequest
	isSet bool
}

func (v NullableUnifiedLipSyncRequest) Get() *UnifiedLipSyncRequest {
	return v.value
}

func (v *NullableUnifiedLipSyncRequest) Set(val *UnifiedLipSyncRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedLipSyncRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedLipSyncRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedLipSyncRequest(val *UnifiedLipSyncRequest) *NullableUnifiedLipSyncRequest {
	return &NullableUnifiedLipSyncRequest{value: val, isSet: true}
}

func (v NullableUnifiedLipSyncRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedLipSyncRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
