/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the SeedanceProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SeedanceProviderOption{}

// SeedanceProviderOption struct for SeedanceProviderOption
type SeedanceProviderOption struct {
	Parameters SeedanceProviderOptionParameters `json:"parameters"`
}

// NewSeedanceProviderOption instantiates a new SeedanceProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSeedanceProviderOption(parameters SeedanceProviderOptionParameters) *SeedanceProviderOption {
	this := SeedanceProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewSeedanceProviderOptionWithDefaults instantiates a new SeedanceProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSeedanceProviderOptionWithDefaults() *SeedanceProviderOption {
	this := SeedanceProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *SeedanceProviderOption) GetParameters() SeedanceProviderOptionParameters {
	if o == nil {
		var ret SeedanceProviderOptionParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *SeedanceProviderOption) GetParametersOk() (*SeedanceProviderOptionParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *SeedanceProviderOption) SetParameters(v SeedanceProviderOptionParameters) {
	o.Parameters = v
}

func (o SeedanceProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SeedanceProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableSeedanceProviderOption struct {
	value *SeedanceProviderOption
	isSet bool
}

func (v NullableSeedanceProviderOption) Get() *SeedanceProviderOption {
	return v.value
}

func (v *NullableSeedanceProviderOption) Set(val *SeedanceProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableSeedanceProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableSeedanceProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeedanceProviderOption(val *SeedanceProviderOption) *NullableSeedanceProviderOption {
	return &NullableSeedanceProviderOption{value: val, isSet: true}
}

func (v NullableSeedanceProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeedanceProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
