/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the ProviderOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderOption{}

// ProviderOption struct for ProviderOption
type ProviderOption struct {
	Parameters map[string]interface{} `json:"parameters"`
}

// NewProviderOption instantiates a new ProviderOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderOption(parameters map[string]interface{}) *ProviderOption {
	this := ProviderOption{}
	this.Parameters = parameters
	return &this
}

// NewProviderOptionWithDefaults instantiates a new ProviderOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderOptionWithDefaults() *ProviderOption {
	this := ProviderOption{}
	return &this
}

// GetParameters returns the Parameters field value
func (o *ProviderOption) GetParameters() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *ProviderOption) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// SetParameters sets field value
func (o *ProviderOption) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

func (o ProviderOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

type NullableProviderOption struct {
	value *ProviderOption
	isSet bool
}

func (v NullableProviderOption) Get() *ProviderOption {
	return v.value
}

func (v *NullableProviderOption) Set(val *ProviderOption) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderOption) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderOption(val *ProviderOption) *NullableProviderOption {
	return &NullableProviderOption{value: val, isSet: true}
}

func (v NullableProviderOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
