/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the UnifiedImageToolRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedImageToolRequest{}

// UnifiedImageToolRequest At least one of image or video is required and is enforced by the server.
type UnifiedImageToolRequest struct {
	Model string `json:"model"`
	// Open legacy scene string.
	Mode               *string          `json:"mode,omitempty"`
	Image              *string          `json:"image,omitempty"`
	Video              *string          `json:"video,omitempty"`
	Creativity         *int64           `json:"creativity,omitempty"`
	TargetResolution   *string          `json:"target_resolution,omitempty"`
	Size               *string          `json:"size,omitempty"`
	OutputFormat       *string          `json:"output_format,omitempty"`
	EnableBase64Output *bool            `json:"enable_base64_output,omitempty"`
	EnableSyncMode     *bool            `json:"enable_sync_mode,omitempty"`
	Provider           *ProviderOptions `json:"provider,omitempty"`
}

// NewUnifiedImageToolRequest instantiates a new UnifiedImageToolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedImageToolRequest(model string) *UnifiedImageToolRequest {
	this := UnifiedImageToolRequest{}
	this.Model = model
	var mode string = "upscale"
	this.Mode = &mode
	return &this
}

// NewUnifiedImageToolRequestWithDefaults instantiates a new UnifiedImageToolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedImageToolRequestWithDefaults() *UnifiedImageToolRequest {
	this := UnifiedImageToolRequest{}
	var mode string = "upscale"
	this.Mode = &mode
	return &this
}

// GetModel returns the Model field value
func (o *UnifiedImageToolRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UnifiedImageToolRequest) SetModel(v string) {
	o.Model = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *UnifiedImageToolRequest) SetMode(v string) {
	o.Mode = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *UnifiedImageToolRequest) SetImage(v string) {
	o.Image = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetVideo() string {
	if o == nil || IsNil(o.Video) {
		var ret string
		return ret
	}
	return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetVideoOk() (*string, bool) {
	if o == nil || IsNil(o.Video) {
		return nil, false
	}
	return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasVideo() bool {
	if o != nil && !IsNil(o.Video) {
		return true
	}

	return false
}

// SetVideo gets a reference to the given string and assigns it to the Video field.
func (o *UnifiedImageToolRequest) SetVideo(v string) {
	o.Video = &v
}

// GetCreativity returns the Creativity field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetCreativity() int64 {
	if o == nil || IsNil(o.Creativity) {
		var ret int64
		return ret
	}
	return *o.Creativity
}

// GetCreativityOk returns a tuple with the Creativity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetCreativityOk() (*int64, bool) {
	if o == nil || IsNil(o.Creativity) {
		return nil, false
	}
	return o.Creativity, true
}

// HasCreativity returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasCreativity() bool {
	if o != nil && !IsNil(o.Creativity) {
		return true
	}

	return false
}

// SetCreativity gets a reference to the given int64 and assigns it to the Creativity field.
func (o *UnifiedImageToolRequest) SetCreativity(v int64) {
	o.Creativity = &v
}

// GetTargetResolution returns the TargetResolution field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetTargetResolution() string {
	if o == nil || IsNil(o.TargetResolution) {
		var ret string
		return ret
	}
	return *o.TargetResolution
}

// GetTargetResolutionOk returns a tuple with the TargetResolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetTargetResolutionOk() (*string, bool) {
	if o == nil || IsNil(o.TargetResolution) {
		return nil, false
	}
	return o.TargetResolution, true
}

// HasTargetResolution returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasTargetResolution() bool {
	if o != nil && !IsNil(o.TargetResolution) {
		return true
	}

	return false
}

// SetTargetResolution gets a reference to the given string and assigns it to the TargetResolution field.
func (o *UnifiedImageToolRequest) SetTargetResolution(v string) {
	o.TargetResolution = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *UnifiedImageToolRequest) SetSize(v string) {
	o.Size = &v
}

// GetOutputFormat returns the OutputFormat field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetOutputFormat() string {
	if o == nil || IsNil(o.OutputFormat) {
		var ret string
		return ret
	}
	return *o.OutputFormat
}

// GetOutputFormatOk returns a tuple with the OutputFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetOutputFormatOk() (*string, bool) {
	if o == nil || IsNil(o.OutputFormat) {
		return nil, false
	}
	return o.OutputFormat, true
}

// HasOutputFormat returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasOutputFormat() bool {
	if o != nil && !IsNil(o.OutputFormat) {
		return true
	}

	return false
}

// SetOutputFormat gets a reference to the given string and assigns it to the OutputFormat field.
func (o *UnifiedImageToolRequest) SetOutputFormat(v string) {
	o.OutputFormat = &v
}

// GetEnableBase64Output returns the EnableBase64Output field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetEnableBase64Output() bool {
	if o == nil || IsNil(o.EnableBase64Output) {
		var ret bool
		return ret
	}
	return *o.EnableBase64Output
}

// GetEnableBase64OutputOk returns a tuple with the EnableBase64Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetEnableBase64OutputOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableBase64Output) {
		return nil, false
	}
	return o.EnableBase64Output, true
}

// HasEnableBase64Output returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasEnableBase64Output() bool {
	if o != nil && !IsNil(o.EnableBase64Output) {
		return true
	}

	return false
}

// SetEnableBase64Output gets a reference to the given bool and assigns it to the EnableBase64Output field.
func (o *UnifiedImageToolRequest) SetEnableBase64Output(v bool) {
	o.EnableBase64Output = &v
}

// GetEnableSyncMode returns the EnableSyncMode field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetEnableSyncMode() bool {
	if o == nil || IsNil(o.EnableSyncMode) {
		var ret bool
		return ret
	}
	return *o.EnableSyncMode
}

// GetEnableSyncModeOk returns a tuple with the EnableSyncMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetEnableSyncModeOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSyncMode) {
		return nil, false
	}
	return o.EnableSyncMode, true
}

// HasEnableSyncMode returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasEnableSyncMode() bool {
	if o != nil && !IsNil(o.EnableSyncMode) {
		return true
	}

	return false
}

// SetEnableSyncMode gets a reference to the given bool and assigns it to the EnableSyncMode field.
func (o *UnifiedImageToolRequest) SetEnableSyncMode(v bool) {
	o.EnableSyncMode = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UnifiedImageToolRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedImageToolRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UnifiedImageToolRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *UnifiedImageToolRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o UnifiedImageToolRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedImageToolRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Video) {
		toSerialize["video"] = o.Video
	}
	if !IsNil(o.Creativity) {
		toSerialize["creativity"] = o.Creativity
	}
	if !IsNil(o.TargetResolution) {
		toSerialize["target_resolution"] = o.TargetResolution
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.OutputFormat) {
		toSerialize["output_format"] = o.OutputFormat
	}
	if !IsNil(o.EnableBase64Output) {
		toSerialize["enable_base64_output"] = o.EnableBase64Output
	}
	if !IsNil(o.EnableSyncMode) {
		toSerialize["enable_sync_mode"] = o.EnableSyncMode
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnifiedImageToolRequest struct {
	value *UnifiedImageToolRequest
	isSet bool
}

func (v NullableUnifiedImageToolRequest) Get() *UnifiedImageToolRequest {
	return v.value
}

func (v *NullableUnifiedImageToolRequest) Set(val *UnifiedImageToolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedImageToolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedImageToolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedImageToolRequest(val *UnifiedImageToolRequest) *NullableUnifiedImageToolRequest {
	return &NullableUnifiedImageToolRequest{value: val, isSet: true}
}

func (v NullableUnifiedImageToolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedImageToolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
