/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the WanProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WanProviderOptionParameters{}

// WanProviderOptionParameters struct for WanProviderOptionParameters
type WanProviderOptionParameters struct {
	EnablePromptExpansion *bool   `json:"enable_prompt_expansion,omitempty"`
	Watermark             *bool   `json:"watermark,omitempty"`
	Mode                  *string `json:"mode,omitempty"`
	ShotType              *string `json:"shot_type,omitempty"`
	N                     *int32  `json:"n,omitempty"`
	NegativePrompt        *string `json:"negative_prompt,omitempty"`
}

// NewWanProviderOptionParameters instantiates a new WanProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWanProviderOptionParameters() *WanProviderOptionParameters {
	this := WanProviderOptionParameters{}
	return &this
}

// NewWanProviderOptionParametersWithDefaults instantiates a new WanProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWanProviderOptionParametersWithDefaults() *WanProviderOptionParameters {
	this := WanProviderOptionParameters{}
	return &this
}

// GetEnablePromptExpansion returns the EnablePromptExpansion field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetEnablePromptExpansion() bool {
	if o == nil || IsNil(o.EnablePromptExpansion) {
		var ret bool
		return ret
	}
	return *o.EnablePromptExpansion
}

// GetEnablePromptExpansionOk returns a tuple with the EnablePromptExpansion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetEnablePromptExpansionOk() (*bool, bool) {
	if o == nil || IsNil(o.EnablePromptExpansion) {
		return nil, false
	}
	return o.EnablePromptExpansion, true
}

// HasEnablePromptExpansion returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasEnablePromptExpansion() bool {
	if o != nil && !IsNil(o.EnablePromptExpansion) {
		return true
	}

	return false
}

// SetEnablePromptExpansion gets a reference to the given bool and assigns it to the EnablePromptExpansion field.
func (o *WanProviderOptionParameters) SetEnablePromptExpansion(v bool) {
	o.EnablePromptExpansion = &v
}

// GetWatermark returns the Watermark field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetWatermark() bool {
	if o == nil || IsNil(o.Watermark) {
		var ret bool
		return ret
	}
	return *o.Watermark
}

// GetWatermarkOk returns a tuple with the Watermark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetWatermarkOk() (*bool, bool) {
	if o == nil || IsNil(o.Watermark) {
		return nil, false
	}
	return o.Watermark, true
}

// HasWatermark returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasWatermark() bool {
	if o != nil && !IsNil(o.Watermark) {
		return true
	}

	return false
}

// SetWatermark gets a reference to the given bool and assigns it to the Watermark field.
func (o *WanProviderOptionParameters) SetWatermark(v bool) {
	o.Watermark = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *WanProviderOptionParameters) SetMode(v string) {
	o.Mode = &v
}

// GetShotType returns the ShotType field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetShotType() string {
	if o == nil || IsNil(o.ShotType) {
		var ret string
		return ret
	}
	return *o.ShotType
}

// GetShotTypeOk returns a tuple with the ShotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetShotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ShotType) {
		return nil, false
	}
	return o.ShotType, true
}

// HasShotType returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasShotType() bool {
	if o != nil && !IsNil(o.ShotType) {
		return true
	}

	return false
}

// SetShotType gets a reference to the given string and assigns it to the ShotType field.
func (o *WanProviderOptionParameters) SetShotType(v string) {
	o.ShotType = &v
}

// GetN returns the N field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetN() int32 {
	if o == nil || IsNil(o.N) {
		var ret int32
		return ret
	}
	return *o.N
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetNOk() (*int32, bool) {
	if o == nil || IsNil(o.N) {
		return nil, false
	}
	return o.N, true
}

// HasN returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasN() bool {
	if o != nil && !IsNil(o.N) {
		return true
	}

	return false
}

// SetN gets a reference to the given int32 and assigns it to the N field.
func (o *WanProviderOptionParameters) SetN(v int32) {
	o.N = &v
}

// GetNegativePrompt returns the NegativePrompt field value if set, zero value otherwise.
func (o *WanProviderOptionParameters) GetNegativePrompt() string {
	if o == nil || IsNil(o.NegativePrompt) {
		var ret string
		return ret
	}
	return *o.NegativePrompt
}

// GetNegativePromptOk returns a tuple with the NegativePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WanProviderOptionParameters) GetNegativePromptOk() (*string, bool) {
	if o == nil || IsNil(o.NegativePrompt) {
		return nil, false
	}
	return o.NegativePrompt, true
}

// HasNegativePrompt returns a boolean if a field has been set.
func (o *WanProviderOptionParameters) HasNegativePrompt() bool {
	if o != nil && !IsNil(o.NegativePrompt) {
		return true
	}

	return false
}

// SetNegativePrompt gets a reference to the given string and assigns it to the NegativePrompt field.
func (o *WanProviderOptionParameters) SetNegativePrompt(v string) {
	o.NegativePrompt = &v
}

func (o WanProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WanProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnablePromptExpansion) {
		toSerialize["enable_prompt_expansion"] = o.EnablePromptExpansion
	}
	if !IsNil(o.Watermark) {
		toSerialize["watermark"] = o.Watermark
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.ShotType) {
		toSerialize["shot_type"] = o.ShotType
	}
	if !IsNil(o.N) {
		toSerialize["n"] = o.N
	}
	if !IsNil(o.NegativePrompt) {
		toSerialize["negative_prompt"] = o.NegativePrompt
	}
	return toSerialize, nil
}

type NullableWanProviderOptionParameters struct {
	value *WanProviderOptionParameters
	isSet bool
}

func (v NullableWanProviderOptionParameters) Get() *WanProviderOptionParameters {
	return v.value
}

func (v *NullableWanProviderOptionParameters) Set(val *WanProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableWanProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableWanProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWanProviderOptionParameters(val *WanProviderOptionParameters) *NullableWanProviderOptionParameters {
	return &NullableWanProviderOptionParameters{value: val, isSet: true}
}

func (v NullableWanProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWanProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
