/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the SeedanceProviderOptionParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SeedanceProviderOptionParameters{}

// SeedanceProviderOptionParameters struct for SeedanceProviderOptionParameters
type SeedanceProviderOptionParameters struct {
	CameraFixed   *bool    `json:"camera_fixed,omitempty"`
	MediaFiles    []string `json:"media_files,omitempty"`
	IsUploadMedia *bool    `json:"is_upload_media,omitempty"`
}

// NewSeedanceProviderOptionParameters instantiates a new SeedanceProviderOptionParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSeedanceProviderOptionParameters() *SeedanceProviderOptionParameters {
	this := SeedanceProviderOptionParameters{}
	return &this
}

// NewSeedanceProviderOptionParametersWithDefaults instantiates a new SeedanceProviderOptionParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSeedanceProviderOptionParametersWithDefaults() *SeedanceProviderOptionParameters {
	this := SeedanceProviderOptionParameters{}
	return &this
}

// GetCameraFixed returns the CameraFixed field value if set, zero value otherwise.
func (o *SeedanceProviderOptionParameters) GetCameraFixed() bool {
	if o == nil || IsNil(o.CameraFixed) {
		var ret bool
		return ret
	}
	return *o.CameraFixed
}

// GetCameraFixedOk returns a tuple with the CameraFixed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SeedanceProviderOptionParameters) GetCameraFixedOk() (*bool, bool) {
	if o == nil || IsNil(o.CameraFixed) {
		return nil, false
	}
	return o.CameraFixed, true
}

// HasCameraFixed returns a boolean if a field has been set.
func (o *SeedanceProviderOptionParameters) HasCameraFixed() bool {
	if o != nil && !IsNil(o.CameraFixed) {
		return true
	}

	return false
}

// SetCameraFixed gets a reference to the given bool and assigns it to the CameraFixed field.
func (o *SeedanceProviderOptionParameters) SetCameraFixed(v bool) {
	o.CameraFixed = &v
}

// GetMediaFiles returns the MediaFiles field value if set, zero value otherwise.
func (o *SeedanceProviderOptionParameters) GetMediaFiles() []string {
	if o == nil || IsNil(o.MediaFiles) {
		var ret []string
		return ret
	}
	return o.MediaFiles
}

// GetMediaFilesOk returns a tuple with the MediaFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SeedanceProviderOptionParameters) GetMediaFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.MediaFiles) {
		return nil, false
	}
	return o.MediaFiles, true
}

// HasMediaFiles returns a boolean if a field has been set.
func (o *SeedanceProviderOptionParameters) HasMediaFiles() bool {
	if o != nil && !IsNil(o.MediaFiles) {
		return true
	}

	return false
}

// SetMediaFiles gets a reference to the given []string and assigns it to the MediaFiles field.
func (o *SeedanceProviderOptionParameters) SetMediaFiles(v []string) {
	o.MediaFiles = v
}

// GetIsUploadMedia returns the IsUploadMedia field value if set, zero value otherwise.
func (o *SeedanceProviderOptionParameters) GetIsUploadMedia() bool {
	if o == nil || IsNil(o.IsUploadMedia) {
		var ret bool
		return ret
	}
	return *o.IsUploadMedia
}

// GetIsUploadMediaOk returns a tuple with the IsUploadMedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SeedanceProviderOptionParameters) GetIsUploadMediaOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUploadMedia) {
		return nil, false
	}
	return o.IsUploadMedia, true
}

// HasIsUploadMedia returns a boolean if a field has been set.
func (o *SeedanceProviderOptionParameters) HasIsUploadMedia() bool {
	if o != nil && !IsNil(o.IsUploadMedia) {
		return true
	}

	return false
}

// SetIsUploadMedia gets a reference to the given bool and assigns it to the IsUploadMedia field.
func (o *SeedanceProviderOptionParameters) SetIsUploadMedia(v bool) {
	o.IsUploadMedia = &v
}

func (o SeedanceProviderOptionParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SeedanceProviderOptionParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CameraFixed) {
		toSerialize["camera_fixed"] = o.CameraFixed
	}
	if !IsNil(o.MediaFiles) {
		toSerialize["media_files"] = o.MediaFiles
	}
	if !IsNil(o.IsUploadMedia) {
		toSerialize["is_upload_media"] = o.IsUploadMedia
	}
	return toSerialize, nil
}

type NullableSeedanceProviderOptionParameters struct {
	value *SeedanceProviderOptionParameters
	isSet bool
}

func (v NullableSeedanceProviderOptionParameters) Get() *SeedanceProviderOptionParameters {
	return v.value
}

func (v *NullableSeedanceProviderOptionParameters) Set(val *SeedanceProviderOptionParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableSeedanceProviderOptionParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableSeedanceProviderOptionParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeedanceProviderOptionParameters(val *SeedanceProviderOptionParameters) *NullableSeedanceProviderOptionParameters {
	return &NullableSeedanceProviderOptionParameters{value: val, isSet: true}
}

func (v NullableSeedanceProviderOptionParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeedanceProviderOptionParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
