/*
GPTProto API

Unified request fields over the GPTProto asynchronous task pipeline. Fields unique to existing GPTProto capabilities are additive extensions. Unknown JSON fields are ignored for forward compatibility. callback_url and provider routing controls are not exposed in this version.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gptproto

import (
	"encoding/json"
)

// checks if the Unified3DRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Unified3DRequest{}

// Unified3DRequest struct for Unified3DRequest
type Unified3DRequest struct {
	Model string `json:"model"`
	// Open legacy scene string.
	Mode          *string          `json:"mode,omitempty"`
	Image         string           `json:"image"`
	FrontImageUrl *string          `json:"front_image_url,omitempty"`
	BackImageUrl  *string          `json:"back_image_url,omitempty"`
	LeftImageUrl  *string          `json:"left_image_url,omitempty"`
	RightImageUrl *string          `json:"right_image_url,omitempty"`
	Provider      *ProviderOptions `json:"provider,omitempty"`
}

// NewUnified3DRequest instantiates a new Unified3DRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnified3DRequest(model string, image string) *Unified3DRequest {
	this := Unified3DRequest{}
	this.Model = model
	var mode string = "image-to-3d"
	this.Mode = &mode
	this.Image = image
	return &this
}

// NewUnified3DRequestWithDefaults instantiates a new Unified3DRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnified3DRequestWithDefaults() *Unified3DRequest {
	this := Unified3DRequest{}
	var mode string = "image-to-3d"
	this.Mode = &mode
	return &this
}

// GetModel returns the Model field value
func (o *Unified3DRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Unified3DRequest) SetModel(v string) {
	o.Model = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *Unified3DRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *Unified3DRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *Unified3DRequest) SetMode(v string) {
	o.Mode = &v
}

// GetImage returns the Image field value
func (o *Unified3DRequest) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *Unified3DRequest) SetImage(v string) {
	o.Image = v
}

// GetFrontImageUrl returns the FrontImageUrl field value if set, zero value otherwise.
func (o *Unified3DRequest) GetFrontImageUrl() string {
	if o == nil || IsNil(o.FrontImageUrl) {
		var ret string
		return ret
	}
	return *o.FrontImageUrl
}

// GetFrontImageUrlOk returns a tuple with the FrontImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetFrontImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FrontImageUrl) {
		return nil, false
	}
	return o.FrontImageUrl, true
}

// HasFrontImageUrl returns a boolean if a field has been set.
func (o *Unified3DRequest) HasFrontImageUrl() bool {
	if o != nil && !IsNil(o.FrontImageUrl) {
		return true
	}

	return false
}

// SetFrontImageUrl gets a reference to the given string and assigns it to the FrontImageUrl field.
func (o *Unified3DRequest) SetFrontImageUrl(v string) {
	o.FrontImageUrl = &v
}

// GetBackImageUrl returns the BackImageUrl field value if set, zero value otherwise.
func (o *Unified3DRequest) GetBackImageUrl() string {
	if o == nil || IsNil(o.BackImageUrl) {
		var ret string
		return ret
	}
	return *o.BackImageUrl
}

// GetBackImageUrlOk returns a tuple with the BackImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetBackImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BackImageUrl) {
		return nil, false
	}
	return o.BackImageUrl, true
}

// HasBackImageUrl returns a boolean if a field has been set.
func (o *Unified3DRequest) HasBackImageUrl() bool {
	if o != nil && !IsNil(o.BackImageUrl) {
		return true
	}

	return false
}

// SetBackImageUrl gets a reference to the given string and assigns it to the BackImageUrl field.
func (o *Unified3DRequest) SetBackImageUrl(v string) {
	o.BackImageUrl = &v
}

// GetLeftImageUrl returns the LeftImageUrl field value if set, zero value otherwise.
func (o *Unified3DRequest) GetLeftImageUrl() string {
	if o == nil || IsNil(o.LeftImageUrl) {
		var ret string
		return ret
	}
	return *o.LeftImageUrl
}

// GetLeftImageUrlOk returns a tuple with the LeftImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetLeftImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LeftImageUrl) {
		return nil, false
	}
	return o.LeftImageUrl, true
}

// HasLeftImageUrl returns a boolean if a field has been set.
func (o *Unified3DRequest) HasLeftImageUrl() bool {
	if o != nil && !IsNil(o.LeftImageUrl) {
		return true
	}

	return false
}

// SetLeftImageUrl gets a reference to the given string and assigns it to the LeftImageUrl field.
func (o *Unified3DRequest) SetLeftImageUrl(v string) {
	o.LeftImageUrl = &v
}

// GetRightImageUrl returns the RightImageUrl field value if set, zero value otherwise.
func (o *Unified3DRequest) GetRightImageUrl() string {
	if o == nil || IsNil(o.RightImageUrl) {
		var ret string
		return ret
	}
	return *o.RightImageUrl
}

// GetRightImageUrlOk returns a tuple with the RightImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetRightImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RightImageUrl) {
		return nil, false
	}
	return o.RightImageUrl, true
}

// HasRightImageUrl returns a boolean if a field has been set.
func (o *Unified3DRequest) HasRightImageUrl() bool {
	if o != nil && !IsNil(o.RightImageUrl) {
		return true
	}

	return false
}

// SetRightImageUrl gets a reference to the given string and assigns it to the RightImageUrl field.
func (o *Unified3DRequest) SetRightImageUrl(v string) {
	o.RightImageUrl = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *Unified3DRequest) GetProvider() ProviderOptions {
	if o == nil || IsNil(o.Provider) {
		var ret ProviderOptions
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unified3DRequest) GetProviderOk() (*ProviderOptions, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *Unified3DRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given ProviderOptions and assigns it to the Provider field.
func (o *Unified3DRequest) SetProvider(v ProviderOptions) {
	o.Provider = &v
}

func (o Unified3DRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Unified3DRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	toSerialize["image"] = o.Image
	if !IsNil(o.FrontImageUrl) {
		toSerialize["front_image_url"] = o.FrontImageUrl
	}
	if !IsNil(o.BackImageUrl) {
		toSerialize["back_image_url"] = o.BackImageUrl
	}
	if !IsNil(o.LeftImageUrl) {
		toSerialize["left_image_url"] = o.LeftImageUrl
	}
	if !IsNil(o.RightImageUrl) {
		toSerialize["right_image_url"] = o.RightImageUrl
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableUnified3DRequest struct {
	value *Unified3DRequest
	isSet bool
}

func (v NullableUnified3DRequest) Get() *Unified3DRequest {
	return v.value
}

func (v *NullableUnified3DRequest) Set(val *Unified3DRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnified3DRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnified3DRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnified3DRequest(val *Unified3DRequest) *NullableUnified3DRequest {
	return &NullableUnified3DRequest{value: val, isSet: true}
}

func (v NullableUnified3DRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnified3DRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
